"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow Executor API
 * Snapflow Executor API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImagesApi = exports.ImagesApiFactory = exports.ImagesApiFp = exports.ImagesApiAxiosParamCreator = void 0;
const tslib_1 = require("tslib");
const axios_1 = tslib_1.__importDefault(require("axios"));
// Some imports not used depending on template conditions
// @ts-ignore
const common_1 = require("../common");
// @ts-ignore
const base_1 = require("../base");
/**
 * ImagesApi - axios parameter creator
 * @export
 */
const ImagesApiAxiosParamCreator = function (configuration) {
    return {
        /**
         * Build a image from a Dockerfile and context hashes
         * @summary Build a image
         * @param {BuildImageRequestDTO} request Build image request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildImage: async (request, options = {}) => {
            // verify required parameter 'request' is not null or undefined
            (0, common_1.assertParamExists)("buildImage", "request", request);
            const localVarPath = `/images/build`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication Bearer required
            await (0, common_1.setApiKeyToObject)(localVarHeaderParameter, "Authorization", configuration);
            localVarHeaderParameter["Content-Type"] = "application/json";
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            localVarRequestOptions.data = (0, common_1.serializeDataIfNeeded)(request, localVarRequestOptions, configuration);
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stream build logs
         * @summary Get build logs
         * @param {string} imageRef Image ID or image ref without the tag
         * @param {boolean} [follow] Whether to follow the log output
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBuildLogs: async (imageRef, follow, options = {}) => {
            // verify required parameter 'imageRef' is not null or undefined
            (0, common_1.assertParamExists)("getBuildLogs", "imageRef", imageRef);
            const localVarPath = `/images/logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication Bearer required
            await (0, common_1.setApiKeyToObject)(localVarHeaderParameter, "Authorization", configuration);
            if (imageRef !== undefined) {
                localVarQueryParameter["imageRef"] = imageRef;
            }
            if (follow !== undefined) {
                localVarQueryParameter["follow"] = follow;
            }
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Check if a specified image exists locally
         * @summary Check if a image exists
         * @param {string} image Image name and tag
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageExists: async (image, options = {}) => {
            // verify required parameter 'image' is not null or undefined
            (0, common_1.assertParamExists)("imageExists", "image", image);
            const localVarPath = `/images/exists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication Bearer required
            await (0, common_1.setApiKeyToObject)(localVarHeaderParameter, "Authorization", configuration);
            if (image !== undefined) {
                localVarQueryParameter["image"] = image;
            }
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Pull a image from a registry
         * @summary Pull a image
         * @param {PullImageRequestDTO} request Pull image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pullImage: async (request, options = {}) => {
            // verify required parameter 'request' is not null or undefined
            (0, common_1.assertParamExists)("pullImage", "request", request);
            const localVarPath = `/images/pull`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication Bearer required
            await (0, common_1.setApiKeyToObject)(localVarHeaderParameter, "Authorization", configuration);
            localVarHeaderParameter["Content-Type"] = "application/json";
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            localVarRequestOptions.data = (0, common_1.serializeDataIfNeeded)(request, localVarRequestOptions, configuration);
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a specified image from the local system
         * @summary Remove a image
         * @param {string} image Image name and tag
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeImage: async (image, options = {}) => {
            // verify required parameter 'image' is not null or undefined
            (0, common_1.assertParamExists)("removeImage", "image", image);
            const localVarPath = `/images/remove`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication Bearer required
            await (0, common_1.setApiKeyToObject)(localVarHeaderParameter, "Authorization", configuration);
            if (image !== undefined) {
                localVarQueryParameter["image"] = image;
            }
            (0, common_1.setSearchParams)(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            return {
                url: (0, common_1.toPathString)(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
exports.ImagesApiAxiosParamCreator = ImagesApiAxiosParamCreator;
/**
 * ImagesApi - functional programming interface
 * @export
 */
const ImagesApiFp = function (configuration) {
    const localVarAxiosParamCreator = (0, exports.ImagesApiAxiosParamCreator)(configuration);
    return {
        /**
         * Build a image from a Dockerfile and context hashes
         * @summary Build a image
         * @param {BuildImageRequestDTO} request Build image request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buildImage(request, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buildImage(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = base_1.operationServerMap["ImagesApi.buildImage"]?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Stream build logs
         * @summary Get build logs
         * @param {string} imageRef Image ID or image ref without the tag
         * @param {boolean} [follow] Whether to follow the log output
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBuildLogs(imageRef, follow, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBuildLogs(imageRef, follow, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = base_1.operationServerMap["ImagesApi.getBuildLogs"]?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Check if a specified image exists locally
         * @summary Check if a image exists
         * @param {string} image Image name and tag
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imageExists(image, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imageExists(image, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = base_1.operationServerMap["ImagesApi.imageExists"]?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Pull a image from a registry
         * @summary Pull a image
         * @param {PullImageRequestDTO} request Pull image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pullImage(request, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pullImage(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = base_1.operationServerMap["ImagesApi.pullImage"]?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove a specified image from the local system
         * @summary Remove a image
         * @param {string} image Image name and tag
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeImage(image, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeImage(image, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = base_1.operationServerMap["ImagesApi.removeImage"]?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => (0, common_1.createRequestFunction)(localVarAxiosArgs, axios_1.default, base_1.BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    };
};
exports.ImagesApiFp = ImagesApiFp;
/**
 * ImagesApi - factory interface
 * @export
 */
const ImagesApiFactory = function (configuration, basePath, axios) {
    const localVarFp = (0, exports.ImagesApiFp)(configuration);
    return {
        /**
         * Build a image from a Dockerfile and context hashes
         * @summary Build a image
         * @param {BuildImageRequestDTO} request Build image request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildImage(request, options) {
            return localVarFp.buildImage(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Stream build logs
         * @summary Get build logs
         * @param {string} imageRef Image ID or image ref without the tag
         * @param {boolean} [follow] Whether to follow the log output
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBuildLogs(imageRef, follow, options) {
            return localVarFp
                .getBuildLogs(imageRef, follow, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * Check if a specified image exists locally
         * @summary Check if a image exists
         * @param {string} image Image name and tag
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageExists(image, options) {
            return localVarFp.imageExists(image, options).then((request) => request(axios, basePath));
        },
        /**
         * Pull a image from a registry
         * @summary Pull a image
         * @param {PullImageRequestDTO} request Pull image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pullImage(request, options) {
            return localVarFp.pullImage(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a specified image from the local system
         * @summary Remove a image
         * @param {string} image Image name and tag
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeImage(image, options) {
            return localVarFp.removeImage(image, options).then((request) => request(axios, basePath));
        },
    };
};
exports.ImagesApiFactory = ImagesApiFactory;
/**
 * ImagesApi - object-oriented interface
 * @export
 * @class ImagesApi
 * @extends {BaseAPI}
 */
class ImagesApi extends base_1.BaseAPI {
    /**
     * Build a image from a Dockerfile and context hashes
     * @summary Build a image
     * @param {BuildImageRequestDTO} request Build image request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    buildImage(request, options) {
        return (0, exports.ImagesApiFp)(this.configuration)
            .buildImage(request, options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     * Stream build logs
     * @summary Get build logs
     * @param {string} imageRef Image ID or image ref without the tag
     * @param {boolean} [follow] Whether to follow the log output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    getBuildLogs(imageRef, follow, options) {
        return (0, exports.ImagesApiFp)(this.configuration)
            .getBuildLogs(imageRef, follow, options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     * Check if a specified image exists locally
     * @summary Check if a image exists
     * @param {string} image Image name and tag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    imageExists(image, options) {
        return (0, exports.ImagesApiFp)(this.configuration)
            .imageExists(image, options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     * Pull a image from a registry
     * @summary Pull a image
     * @param {PullImageRequestDTO} request Pull image
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    pullImage(request, options) {
        return (0, exports.ImagesApiFp)(this.configuration)
            .pullImage(request, options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     * Remove a specified image from the local system
     * @summary Remove a image
     * @param {string} image Image name and tag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    removeImage(image, options) {
        return (0, exports.ImagesApiFp)(this.configuration)
            .removeImage(image, options)
            .then((request) => request(this.axios, this.basePath));
    }
}
exports.ImagesApi = ImagesApi;
//# sourceMappingURL=images-api.js.map