export enum SandboxState {
  CREATING = "creating",
  RESTORING = "restoring",
  DESTROYED = "destroyed",
  DESTROYING = "destroying",
  STARTED = "started",
  STOPPED = "stopped",
  STARTING = "starting",
  STOPPING = "stopping",
  ERROR = "error",
  BUILD_FAILED = "build_failed",
  PENDING_BUILD = "pending_build",
  BUILDING_IMAGE = "building_image",
  UNKNOWN = "unknown",
  PULLING_IMAGE = "pulling_image",
  ARCHIVING = "archiving",
  ARCHIVED = "archived",
}
