/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateExecutor } from '../models';
// @ts-ignore
import type { Executor } from '../models';
// @ts-ignore
import type { ExecutorImageDto } from '../models';
/**
 * ExecutorsApi - axios parameter creator
 * @export
 */
export const ExecutorsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create executor
         * @param {CreateExecutor} createExecutor 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExecutor: async (createExecutor: CreateExecutor, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createExecutor' is not null or undefined
            assertParamExists('createExecutor', 'createExecutor', createExecutor)
            const localVarPath = `/executors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createExecutor, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get executor by sandbox ID
         * @param {string} sandboxId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutorBySandboxId: async (sandboxId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sandboxId' is not null or undefined
            assertParamExists('getExecutorBySandboxId', 'sandboxId', sandboxId)
            const localVarPath = `/executors/by-sandbox/{sandboxId}`
                .replace(`{${"sandboxId"}}`, encodeURIComponent(String(sandboxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get executors by image internal name
         * @param {string} internalName Internal name of the image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutorsByImageInternalName: async (internalName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'internalName' is not null or undefined
            assertParamExists('getExecutorsByImageInternalName', 'internalName', internalName)
            const localVarPath = `/executors/by-image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (internalName !== undefined) {
                localVarQueryParameter['internalName'] = internalName;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all executors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listExecutors: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/executors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update executor scheduling status
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateExecutorScheduling: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateExecutorScheduling', 'id', id)
            const localVarPath = `/executors/{id}/scheduling`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExecutorsApi - functional programming interface
 * @export
 */
export const ExecutorsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExecutorsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create executor
         * @param {CreateExecutor} createExecutor 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createExecutor(createExecutor: CreateExecutor, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createExecutor(createExecutor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecutorsApi.createExecutor']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get executor by sandbox ID
         * @param {string} sandboxId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecutorBySandboxId(sandboxId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Executor>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecutorBySandboxId(sandboxId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecutorsApi.getExecutorBySandboxId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get executors by image internal name
         * @param {string} internalName Internal name of the image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecutorsByImageInternalName(internalName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ExecutorImageDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecutorsByImageInternalName(internalName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecutorsApi.getExecutorsByImageInternalName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all executors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listExecutors(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listExecutors(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecutorsApi.listExecutors']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update executor scheduling status
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateExecutorScheduling(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateExecutorScheduling(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecutorsApi.updateExecutorScheduling']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExecutorsApi - factory interface
 * @export
 */
export const ExecutorsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExecutorsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create executor
         * @param {CreateExecutor} createExecutor 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createExecutor(createExecutor: CreateExecutor, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createExecutor(createExecutor, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get executor by sandbox ID
         * @param {string} sandboxId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutorBySandboxId(sandboxId: string, options?: RawAxiosRequestConfig): AxiosPromise<Executor> {
            return localVarFp.getExecutorBySandboxId(sandboxId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get executors by image internal name
         * @param {string} internalName Internal name of the image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutorsByImageInternalName(internalName: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ExecutorImageDto>> {
            return localVarFp.getExecutorsByImageInternalName(internalName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all executors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listExecutors(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.listExecutors(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update executor scheduling status
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateExecutorScheduling(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateExecutorScheduling(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExecutorsApi - object-oriented interface
 * @export
 * @class ExecutorsApi
 * @extends {BaseAPI}
 */
export class ExecutorsApi extends BaseAPI {
    /**
     * 
     * @summary Create executor
     * @param {CreateExecutor} createExecutor 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutorsApi
     */
    public createExecutor(createExecutor: CreateExecutor, options?: RawAxiosRequestConfig) {
        return ExecutorsApiFp(this.configuration).createExecutor(createExecutor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get executor by sandbox ID
     * @param {string} sandboxId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutorsApi
     */
    public getExecutorBySandboxId(sandboxId: string, options?: RawAxiosRequestConfig) {
        return ExecutorsApiFp(this.configuration).getExecutorBySandboxId(sandboxId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get executors by image internal name
     * @param {string} internalName Internal name of the image
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutorsApi
     */
    public getExecutorsByImageInternalName(internalName: string, options?: RawAxiosRequestConfig) {
        return ExecutorsApiFp(this.configuration).getExecutorsByImageInternalName(internalName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all executors
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutorsApi
     */
    public listExecutors(options?: RawAxiosRequestConfig) {
        return ExecutorsApiFp(this.configuration).listExecutors(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update executor scheduling status
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutorsApi
     */
    public updateExecutorScheduling(id: string, options?: RawAxiosRequestConfig) {
        return ExecutorsApiFp(this.configuration).updateExecutorScheduling(id, options).then((request) => request(this.axios, this.basePath));
    }
}

