/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateBucket } from '../models';
// @ts-ignore
import type { BucketDto } from '../models';
/**
 * BucketsApi - axios parameter creator
 * @export
 */
export const BucketsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new bucket
         * @param {CreateBucket} createBucket 
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBucket: async (createBucket: CreateBucket, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createBucket' is not null or undefined
            assertParamExists('createBucket', 'createBucket', createBucket)
            const localVarPath = `/buckets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBucket, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete bucket
         * @param {string} bucketId ID of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBucket: async (bucketId: string, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bucketId' is not null or undefined
            assertParamExists('deleteBucket', 'bucketId', bucketId)
            const localVarPath = `/buckets/{bucketId}`
                .replace(`{${"bucketId"}}`, encodeURIComponent(String(bucketId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get bucket details
         * @param {string} bucketId ID of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucket: async (bucketId: string, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bucketId' is not null or undefined
            assertParamExists('getBucket', 'bucketId', bucketId)
            const localVarPath = `/buckets/{bucketId}`
                .replace(`{${"bucketId"}}`, encodeURIComponent(String(bucketId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get bucket details by name
         * @param {string} name Name of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucketByName: async (name: string, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getBucketByName', 'name', name)
            const localVarPath = `/buckets/by-name/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all buckets
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [includeDeleted] Include deleted buckets in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBuckets: async (xSnapflowOrganizationID?: string, includeDeleted?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/buckets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (includeDeleted !== undefined) {
                localVarQueryParameter['includeDeleted'] = includeDeleted;
            }


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BucketsApi - functional programming interface
 * @export
 */
export const BucketsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BucketsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new bucket
         * @param {CreateBucket} createBucket 
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBucket(createBucket: CreateBucket, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BucketDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBucket(createBucket, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.createBucket']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete bucket
         * @param {string} bucketId ID of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBucket(bucketId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBucket(bucketId, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.deleteBucket']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get bucket details
         * @param {string} bucketId ID of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBucket(bucketId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BucketDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBucket(bucketId, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.getBucket']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get bucket details by name
         * @param {string} name Name of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBucketByName(name: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BucketDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBucketByName(name, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.getBucketByName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all buckets
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [includeDeleted] Include deleted buckets in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBuckets(xSnapflowOrganizationID?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BucketDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBuckets(xSnapflowOrganizationID, includeDeleted, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.listBuckets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BucketsApi - factory interface
 * @export
 */
export const BucketsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BucketsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new bucket
         * @param {CreateBucket} createBucket 
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBucket(createBucket: CreateBucket, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<BucketDto> {
            return localVarFp.createBucket(createBucket, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete bucket
         * @param {string} bucketId ID of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBucket(bucketId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteBucket(bucketId, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get bucket details
         * @param {string} bucketId ID of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucket(bucketId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<BucketDto> {
            return localVarFp.getBucket(bucketId, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get bucket details by name
         * @param {string} name Name of the bucket
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBucketByName(name: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<BucketDto> {
            return localVarFp.getBucketByName(name, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all buckets
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [includeDeleted] Include deleted buckets in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBuckets(xSnapflowOrganizationID?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<BucketDto>> {
            return localVarFp.listBuckets(xSnapflowOrganizationID, includeDeleted, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BucketsApi - object-oriented interface
 * @export
 * @class BucketsApi
 * @extends {BaseAPI}
 */
export class BucketsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new bucket
     * @param {CreateBucket} createBucket 
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public createBucket(createBucket: CreateBucket, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).createBucket(createBucket, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete bucket
     * @param {string} bucketId ID of the bucket
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public deleteBucket(bucketId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).deleteBucket(bucketId, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get bucket details
     * @param {string} bucketId ID of the bucket
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public getBucket(bucketId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).getBucket(bucketId, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get bucket details by name
     * @param {string} name Name of the bucket
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public getBucketByName(name: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).getBucketByName(name, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all buckets
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [includeDeleted] Include deleted buckets in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public listBuckets(xSnapflowOrganizationID?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).listBuckets(xSnapflowOrganizationID, includeDeleted, options).then((request) => request(this.axios, this.basePath));
    }
}

