/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateVolume } from '../models';
// @ts-ignore
import type { VolumeDto } from '../models';
/**
 * VolumesApi - axios parameter creator
 * @export
 */
export const VolumesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new volume
         * @param {CreateVolume} createVolume 
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVolume: async (createVolume: CreateVolume, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createVolume' is not null or undefined
            assertParamExists('createVolume', 'createVolume', createVolume)
            const localVarPath = `/volumes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createVolume, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete volume
         * @param {string} volumeId ID of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVolume: async (volumeId: string, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'volumeId' is not null or undefined
            assertParamExists('deleteVolume', 'volumeId', volumeId)
            const localVarPath = `/volumes/{volumeId}`
                .replace(`{${"volumeId"}}`, encodeURIComponent(String(volumeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get volume details
         * @param {string} volumeId ID of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVolume: async (volumeId: string, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'volumeId' is not null or undefined
            assertParamExists('getVolume', 'volumeId', volumeId)
            const localVarPath = `/volumes/{volumeId}`
                .replace(`{${"volumeId"}}`, encodeURIComponent(String(volumeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get volume details by name
         * @param {string} name Name of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVolumeByName: async (name: string, xSnapflowOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getVolumeByName', 'name', name)
            const localVarPath = `/volumes/by-name/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all volumes
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [includeDeleted] Include deleted volumes in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVolumes: async (xSnapflowOrganizationID?: string, includeDeleted?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/volumes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (includeDeleted !== undefined) {
                localVarQueryParameter['includeDeleted'] = includeDeleted;
            }


    
            if (xSnapflowOrganizationID != null) {
                localVarHeaderParameter['X-Snapflow-Organization-ID'] = String(xSnapflowOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VolumesApi - functional programming interface
 * @export
 */
export const VolumesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VolumesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new volume
         * @param {CreateVolume} createVolume 
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVolume(createVolume: CreateVolume, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VolumeDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVolume(createVolume, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VolumesApi.createVolume']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete volume
         * @param {string} volumeId ID of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVolume(volumeId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteVolume(volumeId, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VolumesApi.deleteVolume']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get volume details
         * @param {string} volumeId ID of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVolume(volumeId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VolumeDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVolume(volumeId, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VolumesApi.getVolume']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get volume details by name
         * @param {string} name Name of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVolumeByName(name: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VolumeDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVolumeByName(name, xSnapflowOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VolumesApi.getVolumeByName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all volumes
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [includeDeleted] Include deleted volumes in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVolumes(xSnapflowOrganizationID?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<VolumeDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVolumes(xSnapflowOrganizationID, includeDeleted, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VolumesApi.listVolumes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VolumesApi - factory interface
 * @export
 */
export const VolumesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VolumesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new volume
         * @param {CreateVolume} createVolume 
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVolume(createVolume: CreateVolume, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<VolumeDto> {
            return localVarFp.createVolume(createVolume, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete volume
         * @param {string} volumeId ID of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVolume(volumeId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteVolume(volumeId, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get volume details
         * @param {string} volumeId ID of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVolume(volumeId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<VolumeDto> {
            return localVarFp.getVolume(volumeId, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get volume details by name
         * @param {string} name Name of the volume
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVolumeByName(name: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<VolumeDto> {
            return localVarFp.getVolumeByName(name, xSnapflowOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all volumes
         * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [includeDeleted] Include deleted volumes in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVolumes(xSnapflowOrganizationID?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<VolumeDto>> {
            return localVarFp.listVolumes(xSnapflowOrganizationID, includeDeleted, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VolumesApi - object-oriented interface
 * @export
 * @class VolumesApi
 * @extends {BaseAPI}
 */
export class VolumesApi extends BaseAPI {
    /**
     * 
     * @summary Create a new volume
     * @param {CreateVolume} createVolume 
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VolumesApi
     */
    public createVolume(createVolume: CreateVolume, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return VolumesApiFp(this.configuration).createVolume(createVolume, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete volume
     * @param {string} volumeId ID of the volume
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VolumesApi
     */
    public deleteVolume(volumeId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return VolumesApiFp(this.configuration).deleteVolume(volumeId, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get volume details
     * @param {string} volumeId ID of the volume
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VolumesApi
     */
    public getVolume(volumeId: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return VolumesApiFp(this.configuration).getVolume(volumeId, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get volume details by name
     * @param {string} name Name of the volume
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VolumesApi
     */
    public getVolumeByName(name: string, xSnapflowOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return VolumesApiFp(this.configuration).getVolumeByName(name, xSnapflowOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all volumes
     * @param {string} [xSnapflowOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [includeDeleted] Include deleted volumes in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VolumesApi
     */
    public listVolumes(xSnapflowOrganizationID?: string, includeDeleted?: boolean, options?: RawAxiosRequestConfig) {
        return VolumesApiFp(this.configuration).listVolumes(xSnapflowOrganizationID, includeDeleted, options).then((request) => request(this.axios, this.basePath));
    }
}

