/*
Snapflow

Testing SandboxAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apiclient

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_apiclient_SandboxAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SandboxAPIService ArchiveSandbox", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		httpRes, err := apiClient.SandboxAPI.ArchiveSandbox(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService CreateBackup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		resp, httpRes, err := apiClient.SandboxAPI.CreateBackup(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService CreateSandbox", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SandboxAPI.CreateSandbox(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService DeleteSandbox", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		httpRes, err := apiClient.SandboxAPI.DeleteSandbox(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService GetBuildLogs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		httpRes, err := apiClient.SandboxAPI.GetBuildLogs(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService GetPortPreviewUrl", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string
		var port float32

		resp, httpRes, err := apiClient.SandboxAPI.GetPortPreviewUrl(context.Background(), sandboxId, port).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService GetSandbox", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		resp, httpRes, err := apiClient.SandboxAPI.GetSandbox(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService ListSandboxes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SandboxAPI.ListSandboxes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService ReplaceLabels", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		resp, httpRes, err := apiClient.SandboxAPI.ReplaceLabels(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService SetAutoArchiveInterval", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string
		var interval float32

		httpRes, err := apiClient.SandboxAPI.SetAutoArchiveInterval(context.Background(), sandboxId, interval).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService SetAutostopInterval", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string
		var interval float32

		httpRes, err := apiClient.SandboxAPI.SetAutostopInterval(context.Background(), sandboxId, interval).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService StartSandbox", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		resp, httpRes, err := apiClient.SandboxAPI.StartSandbox(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService StopSandbox", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string

		httpRes, err := apiClient.SandboxAPI.StopSandbox(context.Background(), sandboxId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SandboxAPIService UpdatePublicStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sandboxId string
		var isPublic bool

		httpRes, err := apiClient.SandboxAPI.UpdatePublicStatus(context.Background(), sandboxId, isPublic).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
