/*
 * Copyright (c) 2026 Snapflow. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow Node API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CodeFile } from './code-file';

/**
 *
 * @export
 * @interface CodeRunRequest
 */
export interface CodeRunRequest {
	/**
	 *
	 * @type {string}
	 * @memberof CodeRunRequest
	 */
	code?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof CodeRunRequest
	 */
	entrypoint?: string | null;
	/**
	 *
	 * @type {{ [key: string]: string; }}
	 * @memberof CodeRunRequest
	 */
	env?: { [key: string]: string };
	/**
	 *
	 * @type {Array<CodeFile>}
	 * @memberof CodeRunRequest
	 */
	files?: Array<CodeFile> | null;
	/**
	 *
	 * @type {string}
	 * @memberof CodeRunRequest
	 */
	language: string;
	/**
	 *
	 * @type {number}
	 * @memberof CodeRunRequest
	 */
	timeout?: number | null;
	/**
	 *
	 * @type {string}
	 * @memberof CodeRunRequest
	 */
	workDir?: string | null;
}
