// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Snapflow is licensed under the GNU Affero General Public License v3.0.
// You may obtain a copy of the license at https://www.gnu.org/licenses/agpl-3.0.html
//
// SPDX-License-Identifier: AGPL-3.0

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Snapflow Node API",
        version = "0.1.0",
    ),
    paths(
        crate::toolbox::get_version,
        crate::toolbox::get_work_dir,
        crate::toolbox::get_project_dir,
        crate::toolbox::get_user_home_dir,
        crate::toolbox::fs::list_files::list_files,
        crate::toolbox::fs::download_file::download_file,
        crate::toolbox::fs::download_files::bulk_download,
        crate::toolbox::fs::find_in_files::find_in_files,
        crate::toolbox::fs::get_file_info::get_file_info,
        crate::toolbox::fs::search_files::search_files,
        crate::toolbox::fs::create_folder::create_folder,
        crate::toolbox::fs::move_file::move_file,
        crate::toolbox::fs::set_file_permissions::set_file_permissions,
        crate::toolbox::fs::replace_in_files::replace_in_files,
        crate::toolbox::fs::upload_file::upload_file,
        crate::toolbox::fs::upload_files::bulk_upload,
        crate::toolbox::fs::delete_file::delete_file,
        crate::toolbox::process::execute::execute_command,
        crate::toolbox::process::code_run::run_code,
        crate::toolbox::session::controller::list_sessions,
        crate::toolbox::session::controller::create_session,
        crate::toolbox::session::controller::get_session,
        crate::toolbox::session::controller::delete_session,
        crate::toolbox::session::execute::execute_command,
        crate::toolbox::session::controller::get_command,
        crate::toolbox::session::log::get_command_logs,
        crate::toolbox::git::list_branches::list_branches,
        crate::toolbox::git::create_branch::create_branch,
        crate::toolbox::git::delete_branch::delete_branch,
        crate::toolbox::git::history::get_history,
        crate::toolbox::git::status::get_status,
        crate::toolbox::git::add::add_files,
        crate::toolbox::git::checkout::checkout,
        crate::toolbox::git::clone_repository::clone_repo,
        crate::toolbox::git::commit::commit,
        crate::toolbox::git::pull::pull,
        crate::toolbox::git::push::push,
        crate::toolbox::lsp::handlers::start,
        crate::toolbox::lsp::handlers::stop,
        crate::toolbox::lsp::handlers::completions,
        crate::toolbox::lsp::handlers::did_open,
        crate::toolbox::lsp::handlers::did_close,
        crate::toolbox::lsp::handlers::document_symbols,
        crate::toolbox::lsp::handlers::workspace_symbols,
        crate::toolbox::port::get_ports,
        crate::toolbox::port::is_port_in_use,
        crate::computer::routes::get_status,
        crate::computer::routes::start_computer,
        crate::computer::routes::stop_computer,
        crate::computer::routes::get_process_status,
        crate::computer::routes::get_single_process_status,
        crate::computer::routes::restart_process,
        crate::computer::routes::get_process_logs,
        crate::computer::routes::get_process_errors,
        crate::computer::routes::get_screenshot,
        crate::computer::routes::get_region_screenshot,
        crate::computer::routes::get_compressed_screenshot,
        crate::computer::routes::get_compressed_region_screenshot,
        crate::computer::routes::get_mouse_position,
        crate::computer::routes::move_mouse,
        crate::computer::routes::click_mouse,
        crate::computer::routes::drag_mouse,
        crate::computer::routes::scroll_mouse,
        crate::computer::routes::type_text,
        crate::computer::routes::press_key,
        crate::computer::routes::press_hotkey,
        crate::computer::routes::get_display_info,
        crate::computer::routes::get_windows,
    ),
    components(schemas(
        snapflow_errors::ErrorResponse,
        crate::toolbox::fs::types::FileInfo,
        crate::toolbox::fs::types::Match,
        crate::toolbox::fs::types::SearchFilesResponse,
        crate::toolbox::fs::types::ReplaceRequest,
        crate::toolbox::fs::types::ReplaceResult,
        crate::toolbox::fs::download_files::BulkDownloadRequest,
        crate::toolbox::process::types::ExecuteRequest,
        crate::toolbox::process::types::ExecuteResponse,
        crate::toolbox::process::types::CodeRunRequest,
        crate::toolbox::process::types::CodeFile,
        crate::toolbox::process::types::CodeRunResponse,
        crate::toolbox::session::types::CreateSessionRequest,
        crate::toolbox::session::types::SessionExecuteRequest,
        crate::toolbox::session::types::SessionExecuteResponse,
        crate::toolbox::session::types::SessionDto,
        crate::toolbox::session::types::CommandDto,
        crate::toolbox::git::types::GitAddRequest,
        crate::toolbox::git::types::GitCloneRequest,
        crate::toolbox::git::types::GitCommitRequest,
        crate::toolbox::git::types::GitCommitResponse,
        crate::toolbox::git::types::GitBranchRequest,
        crate::toolbox::git::types::GitCheckoutRequest,
        crate::toolbox::git::types::GitRepoRequest,
        crate::toolbox::git::types::ListBranchResponse,
        crate::toolbox::git::types::GitStatus,
        crate::toolbox::git::types::FileStatus,
        crate::toolbox::git::types::GitCommitInfo,
        crate::toolbox::lsp::types::LspServerRequest,
        crate::toolbox::lsp::types::LspDocumentRequest,
        crate::toolbox::lsp::types::LspCompletionParams,
        crate::toolbox::lsp::types::Position,
        crate::toolbox::lsp::types::CompletionContext,
        crate::toolbox::lsp::types::CompletionList,
        crate::toolbox::lsp::types::CompletionItem,
        crate::toolbox::lsp::types::LspSymbol,
        crate::toolbox::lsp::types::LspLocation,
        crate::toolbox::lsp::types::LspRange,
        crate::toolbox::lsp::types::LspPosition,
        crate::toolbox::port::PortList,
        crate::toolbox::port::IsPortInUseResponse,
        crate::computer::screenshot::ScreenshotResponse,
        crate::computer::screenshot::CursorPos,
        crate::computer::mouse::MoveRequest,
        crate::computer::mouse::ClickRequest,
        crate::computer::mouse::DragRequest,
        crate::computer::mouse::ScrollRequest,
        crate::computer::mouse::PositionResponse,
        crate::computer::mouse::ScrollResponse,
        crate::computer::keyboard::TypeTextRequest,
        crate::computer::keyboard::PressKeyRequest,
        crate::computer::keyboard::PressHotkeyRequest,
        crate::computer::display::DisplayInfoResponse,
        crate::computer::display::DisplayInfo,
        crate::computer::display::WindowsResponse,
        crate::computer::display::WindowInfo,
    )),
    tags(
        (name = "info"),
        (name = "file-system"),
        (name = "git"),
        (name = "process"),
        (name = "lsp"),
        (name = "computer-use"),
        (name = "port"),
    )
)]
pub struct ApiDoc;
