/* tslint:disable */

/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateUser
 */
export interface CreateUser {
  /**
   *
   * @type {string}
   * @memberof CreateUser
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CreateUser
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateUser
   */
  email?: string;
  /**
   *
   * @type {boolean}
   * @memberof CreateUser
   */
  emailVerified?: boolean;
  /**
   *
   * @type {string}
   * @memberof CreateUser
   */
  role?: CreateUserRoleEnum;
}

export const CreateUserRoleEnum = {
  ADMIN: "admin",
  USER: "user",
} as const;

export type CreateUserRoleEnum = (typeof CreateUserRoleEnum)[keyof typeof CreateUserRoleEnum];
