/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateApiKey
 */
export interface CreateApiKey {
  /**
   * The name of the API key
   * @type {string}
   * @memberof CreateApiKey
   */
  name: string;
  /**
   * The list of organization resource permissions assigned to the API key
   * @type {Array<string>}
   * @memberof CreateApiKey
   */
  permissions: Array<CreateApiKeyPermissionsEnum>;
  /**
   * When the API key is set to expire
   * @type {Date}
   * @memberof CreateApiKey
   */
  expiresAt?: Date | null;
}

export const CreateApiKeyPermissionsEnum = {
  WRITE_REGISTRIES: "write:registries",
  DELETE_REGISTRIES: "delete:registries",
  WRITE_IMAGES: "write:images",
  DELETE_IMAGES: "delete:images",
  WRITE_SANDBOXES: "write:sandboxes",
  DELETE_SANDBOXES: "delete:sandboxes",
  READ_BUCKETS: "read:buckets",
  WRITE_BUCKETS: "write:buckets",
  DELETE_BUCKETS: "delete:buckets",
} as const;

export type CreateApiKeyPermissionsEnum =
  (typeof CreateApiKeyPermissionsEnum)[keyof typeof CreateApiKeyPermissionsEnum];
