/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateOrganizationInvitation
 */
export interface CreateOrganizationInvitation {
  /**
   * Email address of the inviting user
   * @type {string}
   * @memberof CreateOrganizationInvitation
   */
  email: string;
  /**
   * Organization role of the inviting user
   * @type {string}
   * @memberof CreateOrganizationInvitation
   */
  role: CreateOrganizationInvitationRoleEnum;
  /**
   * Role IDs of the inviting user
   * @type {Array<string>}
   * @memberof CreateOrganizationInvitation
   */
  assignedRoleIds: Array<string>;
  /**
   * Expiration date of the invitation
   * @type {Date}
   * @memberof CreateOrganizationInvitation
   */
  expiresAt?: Date;
}

export const CreateOrganizationInvitationRoleEnum = {
  OWNER: "owner",
  MEMBER: "member",
} as const;

export type CreateOrganizationInvitationRoleEnum =
  (typeof CreateOrganizationInvitationRoleEnum)[keyof typeof CreateOrganizationInvitationRoleEnum];
