/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBuildInfo
 */
export interface CreateBuildInfo {
    /**
     * The Dockerfile content used for the build
     * @type {string}
     * @memberof CreateBuildInfo
     */
    'dockerfileContent': string;
    /**
     * The context hashes used for the build
     * @type {Array<string>}
     * @memberof CreateBuildInfo
     */
    'contextHashes'?: Array<string>;
}

