/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateBuildInfo } from './create-build-info';

/**
 * 
 * @export
 * @interface CreateImage
 */
export interface CreateImage {
    /**
     * The name of the image
     * @type {string}
     * @memberof CreateImage
     */
    'name': string;
    /**
     * The image name of the image
     * @type {string}
     * @memberof CreateImage
     */
    'imageName'?: string;
    /**
     * The entrypoint command for the image
     * @type {Array<string>}
     * @memberof CreateImage
     */
    'entrypoint'?: Array<string>;
    /**
     * Whether the image is general
     * @type {boolean}
     * @memberof CreateImage
     */
    'general'?: boolean;
    /**
     * CPU cores allocated to the resulting sandbox
     * @type {number}
     * @memberof CreateImage
     */
    'cpu'?: number;
    /**
     * GPU units allocated to the resulting sandbox
     * @type {number}
     * @memberof CreateImage
     */
    'gpu'?: number;
    /**
     * Memory allocated to the resulting sandbox in GB
     * @type {number}
     * @memberof CreateImage
     */
    'memory'?: number;
    /**
     * Disk space allocated to the sandbox in GB
     * @type {number}
     * @memberof CreateImage
     */
    'disk'?: number;
    /**
     * Build information for the image
     * @type {CreateBuildInfo}
     * @memberof CreateImage
     */
    'buildInfo'?: CreateBuildInfo;
}

