/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompletionContext } from './completion-context';
// May contain unused imports in some cases
// @ts-ignore
import type { Position } from './position';

/**
 * 
 * @export
 * @interface LspCompletionParams
 */
export interface LspCompletionParams {
    /**
     * Language identifier
     * @type {string}
     * @memberof LspCompletionParams
     */
    'languageId': string;
    /**
     * Path to the project
     * @type {string}
     * @memberof LspCompletionParams
     */
    'pathToProject': string;
    /**
     * Document URI
     * @type {string}
     * @memberof LspCompletionParams
     */
    'uri': string;
    /**
     * 
     * @type {Position}
     * @memberof LspCompletionParams
     */
    'position': Position;
    /**
     * 
     * @type {CompletionContext}
     * @memberof LspCompletionParams
     */
    'context'?: CompletionContext;
}

