/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { LspLocation } from "./lsp-location";

/**
 *
 * @export
 * @interface LspSymbol
 */
export interface LspSymbol {
  /**
   *
   * @type {number}
   * @memberof LspSymbol
   */
  kind: number;
  /**
   *
   * @type {LspLocation}
   * @memberof LspSymbol
   */
  location: LspLocation;
  /**
   *
   * @type {string}
   * @memberof LspSymbol
   */
  name: string;
}
