/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PortPreviewUrl
 */
export interface PortPreviewUrl {
    /**
     * Preview url
     * @type {string}
     * @memberof PortPreviewUrl
     */
    'url': string;
    /**
     * Access token
     * @type {string}
     * @memberof PortPreviewUrl
     */
    'token': string;
    /**
     * Legacy preview url using runner domain
     * @type {string}
     * @memberof PortPreviewUrl
     */
    'legacyProxyUrl'?: string;
}

