/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Position } from "./position";

/**
 *
 * @export
 * @interface Range
 */
export interface Range {
  /**
   *
   * @type {Position}
   * @memberof Range
   */
  start: Position;
  /**
   *
   * @type {Position}
   * @memberof Range
   */
  end: Position;
}
