/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RunnerSnapshotDto
 */
export interface RunnerSnapshotDto {
    /**
     * Runner snapshot ID
     * @type {string}
     * @memberof RunnerSnapshotDto
     */
    'runnerSnapshotId': string;
    /**
     * Runner ID
     * @type {string}
     * @memberof RunnerSnapshotDto
     */
    'runnerId': string;
    /**
     * Runner domain
     * @type {string}
     * @memberof RunnerSnapshotDto
     */
    'runnerDomain': string;
}

