/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The region of the runner
 * @export
 * @enum {string}
 */

export const RunnerRegion = {
    EU: 'eu',
    US: 'us',
    ASIA: 'asia'
} as const;

export type RunnerRegion = typeof RunnerRegion[keyof typeof RunnerRegion];



