/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SessionExecuteResponse
 */
export interface SessionExecuteResponse {
  /**
   * The ID of the executed command
   * @type {string}
   * @memberof SessionExecuteResponse
   */
  cmdId?: string;
  /**
   * The output of the executed command
   * @type {string}
   * @memberof SessionExecuteResponse
   */
  output?: string;
  /**
   * The exit code of the executed command
   * @type {number}
   * @memberof SessionExecuteResponse
   */
  exitCode?: number;
}
