/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@snapflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Bucket state
 * @export
 * @enum {string}
 */

export const BucketState = {
  CREATING: "creating",
  READY: "ready",
  PENDING_CREATE: "pending_create",
  PENDING_DELETE: "pending_delete",
  DELETING: "deleting",
  DELETED: "deleted",
  ERROR: "error",
} as const;

export type BucketState = (typeof BucketState)[keyof typeof BucketState];
