/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow
 * Snapflow AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Workspace
 */
export interface Workspace {
    /**
     * Module ID
     * @type {string}
     * @memberof Workspace
     */
    'id': string;
    /**
     * The id of the module creator
     * @type {string}
     * @memberof Workspace
     */
    'userId': string;
    /**
     * Module name
     * @type {string}
     * @memberof Workspace
     */
    'name': string;
    /**
     * A code for a class
     * @type {string}
     * @memberof Workspace
     */
    'classCode': string;
    /**
     * The color of the workspace
     * @type {string}
     * @memberof Workspace
     */
    'color': string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof Workspace
     */
    'createdAt': Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof Workspace
     */
    'updatedAt': Date;
}

