name: 🐛 Bug Report
description: File a bug report to help us improve Snapflow
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us investigate and resolve the issue quickly.
        
        **Before submitting:**
        - [ ] I have searched existing issues to ensure this bug hasn't been reported already
        - [ ] I have checked the latest version to see if this issue persists
        
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Snapflow is affected?
      options:
        - Backend/API
        - Frontend/UI
        - Database
        - Authentication & Authorization
        - Performance
        - Security
        - DevOps/Infrastructure
        - Build System
        - Testing
        - Documentation
        - Mobile/Responsive
        - Third-party Integration
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Application crashes, data loss, security vulnerability)
        - High (Major functionality broken, affects many users)
        - Medium (Feature doesn't work as expected, workaround available)
        - Low (Minor issue, cosmetic problem)
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: What actually happened?
    validations:
      required: true
      
  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: Any relevant error messages, stack traces, or logs
      placeholder: Paste error messages or logs here...
      render: shell
      
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide your environment details
      placeholder: |
        **Operating System:** (e.g., macOS 13.0, Windows 11, Ubuntu 22.04)
        **Node.js Version:** (e.g., v20.10.0)
        **Bun Version:** (e.g., 1.2.20)
        **Browser:** (e.g., Chrome 119, Safari 17, Firefox 119)
        **Database:** (e.g., PostgreSQL 15.0)
        **Docker Version:** (if applicable)
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots or screen recordings
        - Links to relevant code
        - Configuration details
        - Recent changes that might be related
        
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have provided all the required information above
          required: true
        - label: I have checked that this issue hasn't been reported already
          required: true
        - label: I am willing to help test a fix for this issue
          required: false