// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateImage {
    #[serde(rename = "buildInfo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub build_info: Option<Option<Box<models::CreateBuildInfo>>>,
    #[serde(rename = "cmd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cmd: Option<Option<Vec<String>>>,
    #[serde(rename = "cpu", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<Option<i32>>,
    #[serde(rename = "disk", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub disk: Option<Option<i32>>,
    #[serde(rename = "entrypoint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub entrypoint: Option<Option<Vec<String>>>,
    #[serde(rename = "general", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub general: Option<Option<bool>>,
    #[serde(rename = "gpu", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gpu: Option<Option<i32>>,
    #[serde(rename = "imageName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_name: Option<Option<String>>,
    #[serde(rename = "memory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memory: Option<Option<i32>>,
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateImage {
    pub fn new(name: String) -> CreateImage {
        CreateImage {
            build_info: None,
            cmd: None,
            cpu: None,
            disk: None,
            entrypoint: None,
            general: None,
            gpu: None,
            image_name: None,
            memory: None,
            name,
        }
    }
}

