// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileStatus {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "staging")]
    pub staging: String,
    #[serde(rename = "worktree")]
    pub worktree: String,
    #[serde(rename = "extra")]
    pub extra: String,
}

impl FileStatus {
    pub fn new(name: String, staging: String, worktree: String, extra: String) -> FileStatus {
        FileStatus {
            name,
            staging,
            worktree,
            extra,
        }
    }
}
