// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Image {
    #[serde(
        rename = "buildInfo",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub build_info: Option<Option<Box<models::BuildInfo>>>,
    #[serde(rename = "cpu")]
    pub cpu: i32,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "disk")]
    pub disk: i32,
    #[serde(
        rename = "entrypoint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub entrypoint: Option<Option<Vec<String>>>,
    #[serde(
        rename = "errorReason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error_reason: Option<Option<String>>,
    #[serde(rename = "general")]
    pub general: bool,
    #[serde(rename = "gpu")]
    pub gpu: i32,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "imageName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub image_name: Option<Option<String>>,
    #[serde(
        rename = "lastUsedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_used_at: Option<Option<String>>,
    #[serde(rename = "mem")]
    pub mem: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "organizationId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "size",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub size: Option<Option<f32>>,
    #[serde(rename = "state")]
    pub state: models::ImageState,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl Image {
    pub fn new(
        cpu: i32,
        created_at: String,
        disk: i32,
        general: bool,
        gpu: i32,
        id: uuid::Uuid,
        mem: i32,
        name: String,
        state: models::ImageState,
        updated_at: String,
    ) -> Image {
        Image {
            build_info: None,
            cpu,
            created_at,
            disk,
            entrypoint: None,
            error_reason: None,
            general,
            gpu,
            id,
            image_name: None,
            last_used_at: None,
            mem,
            name,
            organization_id: None,
            size: None,
            state,
            updated_at,
        }
    }
}
