// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "organizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<String>,
    #[serde(rename = "general")]
    pub general: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "imageName", skip_serializing_if = "Option::is_none")]
    pub image_name: Option<String>,
    #[serde(rename = "state")]
    pub state: models::ImageState,
    #[serde(rename = "size", deserialize_with = "Option::deserialize")]
    pub size: Option<f64>,
    #[serde(rename = "entrypoint", deserialize_with = "Option::deserialize")]
    pub entrypoint: Option<Vec<String>>,
    #[serde(rename = "cpu")]
    pub cpu: f64,
    #[serde(rename = "gpu")]
    pub gpu: f64,
    #[serde(rename = "mem")]
    pub mem: f64,
    #[serde(rename = "disk")]
    pub disk: f64,
    #[serde(rename = "errorReason", deserialize_with = "Option::deserialize")]
    pub error_reason: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastUsedAt", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<String>,
    /// Build information for the image
    #[serde(rename = "buildInfo", skip_serializing_if = "Option::is_none")]
    pub build_info: Option<Box<models::BuildInfo>>,
}

impl ImageDto {
    pub fn new(
        id: String,
        general: bool,
        name: String,
        state: models::ImageState,
        size: Option<f64>,
        entrypoint: Option<Vec<String>>,
        cpu: f64,
        gpu: f64,
        mem: f64,
        disk: f64,
        error_reason: Option<String>,
        created_at: String,
        updated_at: String,
        last_used_at: Option<String>,
    ) -> ImageDto {
        ImageDto {
            id,
            organization_id: None,
            general,
            name,
            image_name: None,
            state,
            size,
            entrypoint,
            cpu,
            gpu,
            mem,
            disk,
            error_reason,
            created_at,
            updated_at,
            last_used_at,
            build_info: None,
        }
    }
}
