// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MouseDragRequest {
    /// The starting X coordinate for the drag operation
    #[serde(rename = "startX")]
    pub start_x: f64,
    /// The starting Y coordinate for the drag operation
    #[serde(rename = "startY")]
    pub start_y: f64,
    /// The ending X coordinate for the drag operation
    #[serde(rename = "endX")]
    pub end_x: f64,
    /// The ending Y coordinate for the drag operation
    #[serde(rename = "endY")]
    pub end_y: f64,
    /// The mouse button to use for dragging (left, right, middle). Defaults to left
    #[serde(rename = "button", skip_serializing_if = "Option::is_none")]
    pub button: Option<String>,
}

impl MouseDragRequest {
    pub fn new(start_x: f64, start_y: f64, end_x: f64, end_y: f64) -> MouseDragRequest {
        MouseDragRequest {
            start_x,
            start_y,
            end_x,
            end_y,
            button: None,
        }
    }
}
