// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateQuota {
    #[serde(rename = "bucketQuota", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bucket_quota: Option<Option<i32>>,
    #[serde(rename = "imageQuota", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_quota: Option<Option<i32>>,
    #[serde(rename = "maxCpuPerSandbox", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_cpu_per_sandbox: Option<Option<i32>>,
    #[serde(rename = "maxDiskPerSandbox", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_disk_per_sandbox: Option<Option<i32>>,
    #[serde(rename = "maxImageSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_image_size: Option<Option<i32>>,
    #[serde(rename = "maxMemoryPerSandbox", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_memory_per_sandbox: Option<Option<i32>>,
    #[serde(rename = "totalCpuQuota", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_cpu_quota: Option<Option<i32>>,
    #[serde(rename = "totalDiskQuota", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_disk_quota: Option<Option<i32>>,
    #[serde(rename = "totalMemoryQuota", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_memory_quota: Option<Option<i32>>,
}

impl UpdateQuota {
    pub fn new() -> UpdateQuota {
        UpdateQuota {
            bucket_quota: None,
            image_quota: None,
            max_cpu_per_sandbox: None,
            max_disk_per_sandbox: None,
            max_image_size: None,
            max_memory_per_sandbox: None,
            total_cpu_quota: None,
            total_disk_quota: None,
            total_memory_quota: None,
        }
    }
}

