/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export const BucketState = {
	CREATING: 'creating',
	READY: 'ready',
	PENDING_CREATE: 'pending_create',
	PENDING_DELETE: 'pending_delete',
	DELETING: 'deleting',
	DELETED: 'deleted',
	ERROR: 'error',
} as const;

export type BucketState = (typeof BucketState)[keyof typeof BucketState];
