/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateBuildInfo
 */
export interface CreateBuildInfo {
	/**
	 *
	 * @type {Array<string>}
	 * @memberof CreateBuildInfo
	 */
	contextHashes?: Array<string> | null;
	/**
	 *
	 * @type {string}
	 * @memberof CreateBuildInfo
	 */
	dockerfileContent: string;
}
