/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-expect-error
import type { BuildInfo } from './build-info';
// May contain unused imports in some cases
// @ts-expect-error
import type { ImageState } from './image-state';

/**
 *
 * @export
 * @interface Image
 */
export interface Image {
	/**
	 *
	 * @type {BuildInfo}
	 * @memberof Image
	 */
	buildInfo?: BuildInfo | null;
	/**
	 *
	 * @type {number}
	 * @memberof Image
	 */
	cpu: number;
	/**
	 *
	 * @type {Date}
	 * @memberof Image
	 */
	createdAt: Date;
	/**
	 *
	 * @type {number}
	 * @memberof Image
	 */
	disk: number;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof Image
	 */
	entrypoint?: Array<string> | null;
	/**
	 *
	 * @type {string}
	 * @memberof Image
	 */
	errorReason?: string | null;
	/**
	 *
	 * @type {boolean}
	 * @memberof Image
	 */
	general: boolean;
	/**
	 *
	 * @type {number}
	 * @memberof Image
	 */
	gpu: number;
	/**
	 *
	 * @type {string}
	 * @memberof Image
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof Image
	 */
	imageName?: string | null;
	/**
	 *
	 * @type {Date}
	 * @memberof Image
	 */
	lastUsedAt?: Date | null;
	/**
	 *
	 * @type {number}
	 * @memberof Image
	 */
	mem: number;
	/**
	 *
	 * @type {string}
	 * @memberof Image
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof Image
	 */
	organizationId?: string | null;
	/**
	 *
	 * @type {number}
	 * @memberof Image
	 */
	size?: number | null;
	/**
	 *
	 * @type {ImageState}
	 * @memberof Image
	 */
	state: ImageState;
	/**
	 *
	 * @type {Date}
	 * @memberof Image
	 */
	updatedAt: Date;
}
