/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-expect-error
import type { Sandbox } from './sandbox';

/**
 *
 * @export
 * @interface PaginatedSandboxes
 */
export interface PaginatedSandboxes {
	/**
	 *
	 * @type {Array<Sandbox>}
	 * @memberof PaginatedSandboxes
	 */
	items: Array<Sandbox>;
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedSandboxes
	 */
	page: number;
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedSandboxes
	 */
	total: number;
	/**
	 *
	 * @type {number}
	 * @memberof PaginatedSandboxes
	 */
	totalPages: number;
}
