/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StorageAccess
 */
export interface StorageAccess {
	/**
	 * R2 bucket name
	 * @type {string}
	 * @memberof StorageAccess
	 */
	bucket: string;
	/**
	 * When the pre-signed URL expires (ISO 8601 timestamp)
	 * @type {string}
	 * @memberof StorageAccess
	 */
	expiresAt: string;
	/**
	 * The path where the file will be stored in R2
	 * @type {string}
	 * @memberof StorageAccess
	 */
	filePath: string;
	/**
	 * Organization ID
	 * @type {string}
	 * @memberof StorageAccess
	 */
	organizationId: string;
	/**
	 * Pre-signed URL for uploading objects to R2 storage
	 * @type {string}
	 * @memberof StorageAccess
	 */
	uploadUrl: string;
}
