/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateInvitation
 */
export interface UpdateInvitation {
	/**
	 *
	 * @type {Array<string>}
	 * @memberof UpdateInvitation
	 */
	assignedRoleIds?: Array<string> | null;
	/**
	 *
	 * @type {Date}
	 * @memberof UpdateInvitation
	 */
	expiresAt?: Date | null;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateInvitation
	 */
	role: UpdateInvitationRoleEnum;
}

export const UpdateInvitationRoleEnum = {
	OWNER: 'owner',
	MEMBER: 'member',
} as const;

export type UpdateInvitationRoleEnum =
	(typeof UpdateInvitationRoleEnum)[keyof typeof UpdateInvitationRoleEnum];
