/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WalletOverview
 */
export interface WalletOverview {
	/**
	 *
	 * @type {number}
	 * @memberof WalletOverview
	 */
	balance: number;
	/**
	 *
	 * @type {string}
	 * @memberof WalletOverview
	 */
	tierId: string;
	/**
	 *
	 * @type {string}
	 * @memberof WalletOverview
	 */
	tierName: string;
}
