/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WalletTransaction
 */
export interface WalletTransaction {
	/**
	 *
	 * @type {number}
	 * @memberof WalletTransaction
	 */
	amount: number;
	/**
	 *
	 * @type {number}
	 * @memberof WalletTransaction
	 */
	balanceAfter: number;
	/**
	 *
	 * @type {Date}
	 * @memberof WalletTransaction
	 */
	createdAt: Date;
	/**
	 *
	 * @type {string}
	 * @memberof WalletTransaction
	 */
	description: string;
	/**
	 *
	 * @type {string}
	 * @memberof WalletTransaction
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof WalletTransaction
	 */
	sandboxId?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof WalletTransaction
	 */
	usagePeriodId?: string | null;
}
