/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// @ts-expect-error
import {
	BASE_PATH,
	BaseAPI,
	COLLECTION_FORMATS,
	operationServerMap,
	type RequestArgs,
	RequiredError,
} from '../base';
// Some imports not used depending on template conditions
// @ts-expect-error
import {
	assertParamExists,
	createRequestFunction,
	DUMMY_BASE_URL,
	serializeDataIfNeeded,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	toPathString,
} from '../common';
import type { Configuration } from '../configuration';
// @ts-expect-error
// @ts-expect-error
// @ts-expect-error
import type { ApiKey, ApiKeyCreated, CreateApiKey } from '../models';
/**
 * ApiKeysApi - axios parameter creator
 * @export
 */
export const ApiKeysApiAxiosParamCreator = (configuration?: Configuration) => ({
	/**
	 *
	 * @summary Create API key
	 * @param {CreateApiKey} createApiKey
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 */
	createApiKey: async (
		createApiKey: CreateApiKey,
		xSnapflowOrganizationId?: string,
		options: RawAxiosRequestConfig = {}
	): Promise<RequestArgs> => {
		// verify required parameter 'createApiKey' is not null or undefined
		assertParamExists('createApiKey', 'createApiKey', createApiKey);
		const localVarPath = '/api-keys';
		// use dummy base URL string because the URL constructor only accepts absolute URLs.
		const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
		let baseOptions;
		if (configuration) {
			baseOptions = configuration.baseOptions;
		}

		const localVarRequestOptions = {
			method: 'POST',
			...baseOptions,
			...options,
		};
		const localVarHeaderParameter = {} as any;
		const localVarQueryParameter = {} as any;

		// authentication bearer required
		// http bearer authentication required
		await setBearerAuthToObject(localVarHeaderParameter, configuration);

		localVarHeaderParameter['Content-Type'] = 'application/json';

		if (xSnapflowOrganizationId != null) {
			localVarHeaderParameter['x-snapflow-organization-id'] = String(
				xSnapflowOrganizationId
			);
		}
		setSearchParams(localVarUrlObj, localVarQueryParameter);
		const headersFromBaseOptions =
			baseOptions && baseOptions.headers ? baseOptions.headers : {};
		localVarRequestOptions.headers = {
			...localVarHeaderParameter,
			...headersFromBaseOptions,
			...options.headers,
		};
		localVarRequestOptions.data = serializeDataIfNeeded(
			createApiKey,
			localVarRequestOptions,
			configuration
		);

		return {
			url: toPathString(localVarUrlObj),
			options: localVarRequestOptions,
		};
	},
	/**
	 *
	 * @summary Delete API key by name
	 * @param {string} name Name of the API key
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 */
	deleteApiKey: async (
		name: string,
		xSnapflowOrganizationId?: string,
		options: RawAxiosRequestConfig = {}
	): Promise<RequestArgs> => {
		// verify required parameter 'name' is not null or undefined
		assertParamExists('deleteApiKey', 'name', name);
		const localVarPath = '/api-keys/{name}'.replace(
			`{${'name'}}`,
			encodeURIComponent(String(name))
		);
		// use dummy base URL string because the URL constructor only accepts absolute URLs.
		const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
		let baseOptions;
		if (configuration) {
			baseOptions = configuration.baseOptions;
		}

		const localVarRequestOptions = {
			method: 'DELETE',
			...baseOptions,
			...options,
		};
		const localVarHeaderParameter = {} as any;
		const localVarQueryParameter = {} as any;

		// authentication bearer required
		// http bearer authentication required
		await setBearerAuthToObject(localVarHeaderParameter, configuration);

		if (xSnapflowOrganizationId != null) {
			localVarHeaderParameter['x-snapflow-organization-id'] = String(
				xSnapflowOrganizationId
			);
		}
		setSearchParams(localVarUrlObj, localVarQueryParameter);
		const headersFromBaseOptions =
			baseOptions && baseOptions.headers ? baseOptions.headers : {};
		localVarRequestOptions.headers = {
			...localVarHeaderParameter,
			...headersFromBaseOptions,
			...options.headers,
		};

		return {
			url: toPathString(localVarUrlObj),
			options: localVarRequestOptions,
		};
	},
	/**
	 *
	 * @summary Delete API key for a specific user
	 * @param {string} userId ID of the user
	 * @param {string} name Name of the API key
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 */
	deleteApiKeyForUser: async (
		userId: string,
		name: string,
		xSnapflowOrganizationId?: string,
		options: RawAxiosRequestConfig = {}
	): Promise<RequestArgs> => {
		// verify required parameter 'userId' is not null or undefined
		assertParamExists('deleteApiKeyForUser', 'userId', userId);
		// verify required parameter 'name' is not null or undefined
		assertParamExists('deleteApiKeyForUser', 'name', name);
		const localVarPath = '/api-keys/{user_id}/{name}'
			.replace(`{${'user_id'}}`, encodeURIComponent(String(userId)))
			.replace(`{${'name'}}`, encodeURIComponent(String(name)));
		// use dummy base URL string because the URL constructor only accepts absolute URLs.
		const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
		let baseOptions;
		if (configuration) {
			baseOptions = configuration.baseOptions;
		}

		const localVarRequestOptions = {
			method: 'DELETE',
			...baseOptions,
			...options,
		};
		const localVarHeaderParameter = {} as any;
		const localVarQueryParameter = {} as any;

		// authentication bearer required
		// http bearer authentication required
		await setBearerAuthToObject(localVarHeaderParameter, configuration);

		if (xSnapflowOrganizationId != null) {
			localVarHeaderParameter['x-snapflow-organization-id'] = String(
				xSnapflowOrganizationId
			);
		}
		setSearchParams(localVarUrlObj, localVarQueryParameter);
		const headersFromBaseOptions =
			baseOptions && baseOptions.headers ? baseOptions.headers : {};
		localVarRequestOptions.headers = {
			...localVarHeaderParameter,
			...headersFromBaseOptions,
			...options.headers,
		};

		return {
			url: toPathString(localVarUrlObj),
			options: localVarRequestOptions,
		};
	},
	/**
	 *
	 * @summary Get API key by name
	 * @param {string} name Name of the API key
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 */
	getApiKey: async (
		name: string,
		xSnapflowOrganizationId?: string,
		options: RawAxiosRequestConfig = {}
	): Promise<RequestArgs> => {
		// verify required parameter 'name' is not null or undefined
		assertParamExists('getApiKey', 'name', name);
		const localVarPath = '/api-keys/{name}'.replace(
			`{${'name'}}`,
			encodeURIComponent(String(name))
		);
		// use dummy base URL string because the URL constructor only accepts absolute URLs.
		const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
		let baseOptions;
		if (configuration) {
			baseOptions = configuration.baseOptions;
		}

		const localVarRequestOptions = {
			method: 'GET',
			...baseOptions,
			...options,
		};
		const localVarHeaderParameter = {} as any;
		const localVarQueryParameter = {} as any;

		// authentication bearer required
		// http bearer authentication required
		await setBearerAuthToObject(localVarHeaderParameter, configuration);

		if (xSnapflowOrganizationId != null) {
			localVarHeaderParameter['x-snapflow-organization-id'] = String(
				xSnapflowOrganizationId
			);
		}
		setSearchParams(localVarUrlObj, localVarQueryParameter);
		const headersFromBaseOptions =
			baseOptions && baseOptions.headers ? baseOptions.headers : {};
		localVarRequestOptions.headers = {
			...localVarHeaderParameter,
			...headersFromBaseOptions,
			...options.headers,
		};

		return {
			url: toPathString(localVarUrlObj),
			options: localVarRequestOptions,
		};
	},
	/**
	 *
	 * @summary Get current API key\'s details
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 */
	getCurrentApiKey: async (
		xSnapflowOrganizationId?: string,
		options: RawAxiosRequestConfig = {}
	): Promise<RequestArgs> => {
		const localVarPath = '/api-keys/current';
		// use dummy base URL string because the URL constructor only accepts absolute URLs.
		const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
		let baseOptions;
		if (configuration) {
			baseOptions = configuration.baseOptions;
		}

		const localVarRequestOptions = {
			method: 'GET',
			...baseOptions,
			...options,
		};
		const localVarHeaderParameter = {} as any;
		const localVarQueryParameter = {} as any;

		// authentication bearer required
		// http bearer authentication required
		await setBearerAuthToObject(localVarHeaderParameter, configuration);

		if (xSnapflowOrganizationId != null) {
			localVarHeaderParameter['x-snapflow-organization-id'] = String(
				xSnapflowOrganizationId
			);
		}
		setSearchParams(localVarUrlObj, localVarQueryParameter);
		const headersFromBaseOptions =
			baseOptions && baseOptions.headers ? baseOptions.headers : {};
		localVarRequestOptions.headers = {
			...localVarHeaderParameter,
			...headersFromBaseOptions,
			...options.headers,
		};

		return {
			url: toPathString(localVarUrlObj),
			options: localVarRequestOptions,
		};
	},
	/**
	 *
	 * @summary List API keys
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 */
	listApiKeys: async (
		xSnapflowOrganizationId?: string,
		options: RawAxiosRequestConfig = {}
	): Promise<RequestArgs> => {
		const localVarPath = '/api-keys';
		// use dummy base URL string because the URL constructor only accepts absolute URLs.
		const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
		let baseOptions;
		if (configuration) {
			baseOptions = configuration.baseOptions;
		}

		const localVarRequestOptions = {
			method: 'GET',
			...baseOptions,
			...options,
		};
		const localVarHeaderParameter = {} as any;
		const localVarQueryParameter = {} as any;

		// authentication bearer required
		// http bearer authentication required
		await setBearerAuthToObject(localVarHeaderParameter, configuration);

		if (xSnapflowOrganizationId != null) {
			localVarHeaderParameter['x-snapflow-organization-id'] = String(
				xSnapflowOrganizationId
			);
		}
		setSearchParams(localVarUrlObj, localVarQueryParameter);
		const headersFromBaseOptions =
			baseOptions && baseOptions.headers ? baseOptions.headers : {};
		localVarRequestOptions.headers = {
			...localVarHeaderParameter,
			...headersFromBaseOptions,
			...options.headers,
		};

		return {
			url: toPathString(localVarUrlObj),
			options: localVarRequestOptions,
		};
	},
});

/**
 * ApiKeysApi - functional programming interface
 * @export
 */
export const ApiKeysApiFp = (configuration?: Configuration) => {
	const localVarAxiosParamCreator = ApiKeysApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @summary Create API key
		 * @param {CreateApiKey} createApiKey
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async createApiKey(
			createApiKey: CreateApiKey,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiKeyCreated>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.createApiKey(
				createApiKey,
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ApiKeysApi.createApiKey']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Delete API key by name
		 * @param {string} name Name of the API key
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteApiKey(
			name: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.deleteApiKey(
				name,
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ApiKeysApi.deleteApiKey']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Delete API key for a specific user
		 * @param {string} userId ID of the user
		 * @param {string} name Name of the API key
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteApiKeyForUser(
			userId: string,
			name: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.deleteApiKeyForUser(
					userId,
					name,
					xSnapflowOrganizationId,
					options
				);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ApiKeysApi.deleteApiKeyForUser']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Get API key by name
		 * @param {string} name Name of the API key
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getApiKey(
			name: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiKey>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getApiKey(
				name,
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ApiKeysApi.getApiKey']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Get current API key\'s details
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getCurrentApiKey(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiKey>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.getCurrentApiKey(
					xSnapflowOrganizationId,
					options
				);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ApiKeysApi.getCurrentApiKey']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary List API keys
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async listApiKeys(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApiKey>>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.listApiKeys(
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ApiKeysApi.listApiKeys']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
	};
};

/**
 * ApiKeysApi - factory interface
 * @export
 */
export const ApiKeysApiFactory = (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) => {
	const localVarFp = ApiKeysApiFp(configuration);
	return {
		/**
		 *
		 * @summary Create API key
		 * @param {CreateApiKey} createApiKey
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		createApiKey(
			createApiKey: CreateApiKey,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<ApiKeyCreated> {
			return localVarFp
				.createApiKey(createApiKey, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Delete API key by name
		 * @param {string} name Name of the API key
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteApiKey(
			name: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.deleteApiKey(name, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Delete API key for a specific user
		 * @param {string} userId ID of the user
		 * @param {string} name Name of the API key
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteApiKeyForUser(
			userId: string,
			name: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.deleteApiKeyForUser(userId, name, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Get API key by name
		 * @param {string} name Name of the API key
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getApiKey(
			name: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<ApiKey> {
			return localVarFp
				.getApiKey(name, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Get current API key\'s details
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getCurrentApiKey(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<ApiKey> {
			return localVarFp
				.getCurrentApiKey(xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary List API keys
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		listApiKeys(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Array<ApiKey>> {
			return localVarFp
				.listApiKeys(xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
	};
};

/**
 * ApiKeysApi - object-oriented interface
 * @export
 * @class ApiKeysApi
 * @extends {BaseAPI}
 */
export class ApiKeysApi extends BaseAPI {
	/**
	 *
	 * @summary Create API key
	 * @param {CreateApiKey} createApiKey
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ApiKeysApi
	 */
	public createApiKey(
		createApiKey: CreateApiKey,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return ApiKeysApiFp(this.configuration)
			.createApiKey(createApiKey, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Delete API key by name
	 * @param {string} name Name of the API key
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ApiKeysApi
	 */
	public deleteApiKey(
		name: string,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return ApiKeysApiFp(this.configuration)
			.deleteApiKey(name, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Delete API key for a specific user
	 * @param {string} userId ID of the user
	 * @param {string} name Name of the API key
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ApiKeysApi
	 */
	public deleteApiKeyForUser(
		userId: string,
		name: string,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return ApiKeysApiFp(this.configuration)
			.deleteApiKeyForUser(userId, name, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Get API key by name
	 * @param {string} name Name of the API key
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ApiKeysApi
	 */
	public getApiKey(
		name: string,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return ApiKeysApiFp(this.configuration)
			.getApiKey(name, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Get current API key\'s details
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ApiKeysApi
	 */
	public getCurrentApiKey(
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return ApiKeysApiFp(this.configuration)
			.getCurrentApiKey(xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary List API keys
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ApiKeysApi
	 */
	public listApiKeys(
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return ApiKeysApiFp(this.configuration)
			.listApiKeys(xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}
}
