/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	serializeDataIfNeeded,
	toPathString,
	createRequestFunction,
} from '../common';
// @ts-ignore
import {
	BASE_PATH,
	COLLECTION_FORMATS,
	type RequestArgs,
	BaseAPI,
	RequiredError,
	operationServerMap,
} from '../base';
// @ts-ignore
import type { CreateRegistry } from '../models';
// @ts-ignore
import type { Registry } from '../models';
// @ts-ignore
import type { RegistryPushAccess } from '../models';
// @ts-ignore
import type { UpdateRegistry } from '../models';
/**
 * RegistryApi - axios parameter creator
 * @export
 */
export const RegistryApiAxiosParamCreator = function (
	configuration?: Configuration
) {
	return {
		/**
		 *
		 * @summary Create registry
		 * @param {CreateRegistry} createRegistry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		createRegistry: async (
			createRegistry: CreateRegistry,
			xSnapflowOrganizationId?: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'createRegistry' is not null or undefined
			assertParamExists('createRegistry', 'createRegistry', createRegistry);
			const localVarPath = `/registry`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearer required
			// http bearer authentication required
			await setBearerAuthToObject(localVarHeaderParameter, configuration);

			localVarHeaderParameter['Content-Type'] = 'application/json';

			if (xSnapflowOrganizationId != null) {
				localVarHeaderParameter['x-snapflow-organization-id'] = String(
					xSnapflowOrganizationId
				);
			}
			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				createRegistry,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @summary Delete registry
		 * @param {string} id ID of the container registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteRegistry: async (
			id: string,
			xSnapflowOrganizationId?: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('deleteRegistry', 'id', id);
			const localVarPath = `/registry/{id}`.replace(
				`{${'id'}}`,
				encodeURIComponent(String(id))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'DELETE',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearer required
			// http bearer authentication required
			await setBearerAuthToObject(localVarHeaderParameter, configuration);

			if (xSnapflowOrganizationId != null) {
				localVarHeaderParameter['x-snapflow-organization-id'] = String(
					xSnapflowOrganizationId
				);
			}
			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @summary Get registry
		 * @param {string} id ID of the registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getRegistry: async (
			id: string,
			xSnapflowOrganizationId?: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('getRegistry', 'id', id);
			const localVarPath = `/registry/{id}`.replace(
				`{${'id'}}`,
				encodeURIComponent(String(id))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearer required
			// http bearer authentication required
			await setBearerAuthToObject(localVarHeaderParameter, configuration);

			if (xSnapflowOrganizationId != null) {
				localVarHeaderParameter['x-snapflow-organization-id'] = String(
					xSnapflowOrganizationId
				);
			}
			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @summary Get temporary registry access for pushing images
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getTransientPushAccess: async (
			xSnapflowOrganizationId?: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			const localVarPath = `/registry/registry-push-access`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearer required
			// http bearer authentication required
			await setBearerAuthToObject(localVarHeaderParameter, configuration);

			if (xSnapflowOrganizationId != null) {
				localVarHeaderParameter['x-snapflow-organization-id'] = String(
					xSnapflowOrganizationId
				);
			}
			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @summary List registries
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		listRegistries: async (
			xSnapflowOrganizationId?: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			const localVarPath = `/registry`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearer required
			// http bearer authentication required
			await setBearerAuthToObject(localVarHeaderParameter, configuration);

			if (xSnapflowOrganizationId != null) {
				localVarHeaderParameter['x-snapflow-organization-id'] = String(
					xSnapflowOrganizationId
				);
			}
			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @summary Set default registry
		 * @param {string} id ID of the container registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		setDefaultRegistry: async (
			id: string,
			xSnapflowOrganizationId?: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('setDefaultRegistry', 'id', id);
			const localVarPath = `/registry/{id}/set-default`.replace(
				`{${'id'}}`,
				encodeURIComponent(String(id))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearer required
			// http bearer authentication required
			await setBearerAuthToObject(localVarHeaderParameter, configuration);

			if (xSnapflowOrganizationId != null) {
				localVarHeaderParameter['x-snapflow-organization-id'] = String(
					xSnapflowOrganizationId
				);
			}
			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @summary Update registry
		 * @param {string} id ID of the registry
		 * @param {UpdateRegistry} updateRegistry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		updateRegistry: async (
			id: string,
			updateRegistry: UpdateRegistry,
			xSnapflowOrganizationId?: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'id' is not null or undefined
			assertParamExists('updateRegistry', 'id', id);
			// verify required parameter 'updateRegistry' is not null or undefined
			assertParamExists('updateRegistry', 'updateRegistry', updateRegistry);
			const localVarPath = `/registry/{id}`.replace(
				`{${'id'}}`,
				encodeURIComponent(String(id))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'PATCH',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			// authentication bearer required
			// http bearer authentication required
			await setBearerAuthToObject(localVarHeaderParameter, configuration);

			localVarHeaderParameter['Content-Type'] = 'application/json';

			if (xSnapflowOrganizationId != null) {
				localVarHeaderParameter['x-snapflow-organization-id'] = String(
					xSnapflowOrganizationId
				);
			}
			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				updateRegistry,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
	};
};

/**
 * RegistryApi - functional programming interface
 * @export
 */
export const RegistryApiFp = function (configuration?: Configuration) {
	const localVarAxiosParamCreator = RegistryApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @summary Create registry
		 * @param {CreateRegistry} createRegistry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async createRegistry(
			createRegistry: CreateRegistry,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Registry>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.createRegistry(
				createRegistry,
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['RegistryApi.createRegistry']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Delete registry
		 * @param {string} id ID of the container registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteRegistry(
			id: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRegistry(
				id,
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['RegistryApi.deleteRegistry']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Get registry
		 * @param {string} id ID of the registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getRegistry(
			id: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Registry>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getRegistry(
				id,
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['RegistryApi.getRegistry']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Get temporary registry access for pushing images
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getTransientPushAccess(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<RegistryPushAccess>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.getTransientPushAccess(
					xSnapflowOrganizationId,
					options
				);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['RegistryApi.getTransientPushAccess']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary List registries
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async listRegistries(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<Array<Registry>>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.listRegistries(
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['RegistryApi.listRegistries']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Set default registry
		 * @param {string} id ID of the container registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async setDefaultRegistry(
			id: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Registry>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.setDefaultRegistry(
					id,
					xSnapflowOrganizationId,
					options
				);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['RegistryApi.setDefaultRegistry']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @summary Update registry
		 * @param {string} id ID of the registry
		 * @param {UpdateRegistry} updateRegistry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async updateRegistry(
			id: string,
			updateRegistry: UpdateRegistry,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Registry>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.updateRegistry(
				id,
				updateRegistry,
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['RegistryApi.updateRegistry']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
	};
};

/**
 * RegistryApi - factory interface
 * @export
 */
export const RegistryApiFactory = function (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) {
	const localVarFp = RegistryApiFp(configuration);
	return {
		/**
		 *
		 * @summary Create registry
		 * @param {CreateRegistry} createRegistry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		createRegistry(
			createRegistry: CreateRegistry,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Registry> {
			return localVarFp
				.createRegistry(createRegistry, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Delete registry
		 * @param {string} id ID of the container registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteRegistry(
			id: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.deleteRegistry(id, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Get registry
		 * @param {string} id ID of the registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getRegistry(
			id: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Registry> {
			return localVarFp
				.getRegistry(id, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Get temporary registry access for pushing images
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getTransientPushAccess(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<RegistryPushAccess> {
			return localVarFp
				.getTransientPushAccess(xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary List registries
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		listRegistries(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Array<Registry>> {
			return localVarFp
				.listRegistries(xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Set default registry
		 * @param {string} id ID of the container registry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		setDefaultRegistry(
			id: string,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Registry> {
			return localVarFp
				.setDefaultRegistry(id, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @summary Update registry
		 * @param {string} id ID of the registry
		 * @param {UpdateRegistry} updateRegistry
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		updateRegistry(
			id: string,
			updateRegistry: UpdateRegistry,
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Registry> {
			return localVarFp
				.updateRegistry(id, updateRegistry, xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
	};
};

/**
 * RegistryApi - object-oriented interface
 * @export
 * @class RegistryApi
 * @extends {BaseAPI}
 */
export class RegistryApi extends BaseAPI {
	/**
	 *
	 * @summary Create registry
	 * @param {CreateRegistry} createRegistry
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof RegistryApi
	 */
	public createRegistry(
		createRegistry: CreateRegistry,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return RegistryApiFp(this.configuration)
			.createRegistry(createRegistry, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Delete registry
	 * @param {string} id ID of the container registry
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof RegistryApi
	 */
	public deleteRegistry(
		id: string,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return RegistryApiFp(this.configuration)
			.deleteRegistry(id, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Get registry
	 * @param {string} id ID of the registry
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof RegistryApi
	 */
	public getRegistry(
		id: string,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return RegistryApiFp(this.configuration)
			.getRegistry(id, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Get temporary registry access for pushing images
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof RegistryApi
	 */
	public getTransientPushAccess(
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return RegistryApiFp(this.configuration)
			.getTransientPushAccess(xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary List registries
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof RegistryApi
	 */
	public listRegistries(
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return RegistryApiFp(this.configuration)
			.listRegistries(xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Set default registry
	 * @param {string} id ID of the container registry
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof RegistryApi
	 */
	public setDefaultRegistry(
		id: string,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return RegistryApiFp(this.configuration)
			.setDefaultRegistry(id, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @summary Update registry
	 * @param {string} id ID of the registry
	 * @param {UpdateRegistry} updateRegistry
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof RegistryApi
	 */
	public updateRegistry(
		id: string,
		updateRegistry: UpdateRegistry,
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return RegistryApiFp(this.configuration)
			.updateRegistry(id, updateRegistry, xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}
}
