/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// @ts-expect-error
import {
	BASE_PATH,
	BaseAPI,
	COLLECTION_FORMATS,
	operationServerMap,
	type RequestArgs,
	RequiredError,
} from '../base';
// Some imports not used depending on template conditions
// @ts-expect-error
import {
	assertParamExists,
	createRequestFunction,
	DUMMY_BASE_URL,
	serializeDataIfNeeded,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	toPathString,
} from '../common';
import type { Configuration } from '../configuration';
// @ts-expect-error
import type { StorageAccess } from '../models';
/**
 * StorageApi - axios parameter creator
 * @export
 */
export const StorageApiAxiosParamCreator = (configuration?: Configuration) => ({
	/**
	 * Returns a pre-signed URL scoped to the organization\'s storage path. The URL expires after a short period.
	 * @summary Get pre-signed URL for uploading objects to Cloudflare R2
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 */
	getPushAccess: async (
		xSnapflowOrganizationId?: string,
		options: RawAxiosRequestConfig = {}
	): Promise<RequestArgs> => {
		const localVarPath = '/storage/push-access';
		// use dummy base URL string because the URL constructor only accepts absolute URLs.
		const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
		let baseOptions;
		if (configuration) {
			baseOptions = configuration.baseOptions;
		}

		const localVarRequestOptions = {
			method: 'GET',
			...baseOptions,
			...options,
		};
		const localVarHeaderParameter = {} as any;
		const localVarQueryParameter = {} as any;

		// authentication bearer required
		// http bearer authentication required
		await setBearerAuthToObject(localVarHeaderParameter, configuration);

		if (xSnapflowOrganizationId != null) {
			localVarHeaderParameter['x-snapflow-organization-id'] = String(
				xSnapflowOrganizationId
			);
		}
		setSearchParams(localVarUrlObj, localVarQueryParameter);
		const headersFromBaseOptions =
			baseOptions && baseOptions.headers ? baseOptions.headers : {};
		localVarRequestOptions.headers = {
			...localVarHeaderParameter,
			...headersFromBaseOptions,
			...options.headers,
		};

		return {
			url: toPathString(localVarUrlObj),
			options: localVarRequestOptions,
		};
	},
});

/**
 * StorageApi - functional programming interface
 * @export
 */
export const StorageApiFp = (configuration?: Configuration) => {
	const localVarAxiosParamCreator = StorageApiAxiosParamCreator(configuration);
	return {
		/**
		 * Returns a pre-signed URL scoped to the organization\'s storage path. The URL expires after a short period.
		 * @summary Get pre-signed URL for uploading objects to Cloudflare R2
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getPushAccess(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StorageAccess>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getPushAccess(
				xSnapflowOrganizationId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['StorageApi.getPushAccess']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
	};
};

/**
 * StorageApi - factory interface
 * @export
 */
export const StorageApiFactory = (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) => {
	const localVarFp = StorageApiFp(configuration);
	return {
		/**
		 * Returns a pre-signed URL scoped to the organization\'s storage path. The URL expires after a short period.
		 * @summary Get pre-signed URL for uploading objects to Cloudflare R2
		 * @param {string} [xSnapflowOrganizationId] Organization ID
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getPushAccess(
			xSnapflowOrganizationId?: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<StorageAccess> {
			return localVarFp
				.getPushAccess(xSnapflowOrganizationId, options)
				.then((request) => request(axios, basePath));
		},
	};
};

/**
 * StorageApi - object-oriented interface
 * @export
 * @class StorageApi
 * @extends {BaseAPI}
 */
export class StorageApi extends BaseAPI {
	/**
	 * Returns a pre-signed URL scoped to the organization\'s storage path. The URL expires after a short period.
	 * @summary Get pre-signed URL for uploading objects to Cloudflare R2
	 * @param {string} [xSnapflowOrganizationId] Organization ID
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof StorageApi
	 */
	public getPushAccess(
		xSnapflowOrganizationId?: string,
		options?: RawAxiosRequestConfig
	) {
		return StorageApiFp(this.configuration)
			.getPushAccess(xSnapflowOrganizationId, options)
			.then((request) => request(this.axios, this.basePath));
	}
}
