/*
 * Copyright (c) 2026 Snapflow. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Copyright 2025 Snapflow
 * SPDX-License-Identifier: Apache-2.0
 */

/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	serializeDataIfNeeded,
	toPathString,
	createRequestFunction,
} from '../common';
// @ts-ignore
import {
	BASE_PATH,
	COLLECTION_FORMATS,
	type RequestArgs,
	BaseAPI,
	RequiredError,
	operationServerMap,
} from '../base';
// @ts-ignore
import type { CodeRunRequest } from '../models';
// @ts-ignore
import type { CodeRunResponse } from '../models';
// @ts-ignore
import type { CommandDto } from '../models';
// @ts-ignore
import type { CreateSessionRequest } from '../models';
// @ts-ignore
import type { ExecuteRequest } from '../models';
// @ts-ignore
import type { ExecuteResponse } from '../models';
// @ts-ignore
import type { SessionDto } from '../models';
// @ts-ignore
import type { SessionExecuteRequest } from '../models';
// @ts-ignore
import type { SessionExecuteResponse } from '../models';
/**
 * ToolboxProcessApi - axios parameter creator
 * @export
 */
export const ToolboxProcessApiAxiosParamCreator = function (
	configuration?: Configuration
) {
	return {
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {CreateSessionRequest} createSessionRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		createSession: async (
			sandboxId: string,
			createSessionRequest: CreateSessionRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('createSession', 'sandboxId', sandboxId);
			// verify required parameter 'createSessionRequest' is not null or undefined
			assertParamExists(
				'createSession',
				'createSessionRequest',
				createSessionRequest
			);
			const localVarPath = `/toolbox/{sandboxId}/process/session`.replace(
				`{${'sandboxId'}}`,
				encodeURIComponent(String(sandboxId))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				createSessionRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteSession: async (
			sandboxId: string,
			sessionId: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('deleteSession', 'sandboxId', sandboxId);
			// verify required parameter 'sessionId' is not null or undefined
			assertParamExists('deleteSession', 'sessionId', sessionId);
			const localVarPath = `/toolbox/{sandboxId}/process/session/{sessionId}`
				.replace(`{${'sandboxId'}}`, encodeURIComponent(String(sandboxId)))
				.replace(`{${'sessionId'}}`, encodeURIComponent(String(sessionId)));
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'DELETE',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {ExecuteRequest} executeRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		executeCommand: async (
			sandboxId: string,
			executeRequest: ExecuteRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('executeCommand', 'sandboxId', sandboxId);
			// verify required parameter 'executeRequest' is not null or undefined
			assertParamExists('executeCommand', 'executeRequest', executeRequest);
			const localVarPath = `/toolbox/{sandboxId}/process/execute`.replace(
				`{${'sandboxId'}}`,
				encodeURIComponent(String(sandboxId))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				executeRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {string} commandId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getCommand: async (
			sandboxId: string,
			sessionId: string,
			commandId: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('getCommand', 'sandboxId', sandboxId);
			// verify required parameter 'sessionId' is not null or undefined
			assertParamExists('getCommand', 'sessionId', sessionId);
			// verify required parameter 'commandId' is not null or undefined
			assertParamExists('getCommand', 'commandId', commandId);
			const localVarPath =
				`/toolbox/{sandboxId}/process/session/{sessionId}/command/{commandId}`
					.replace(`{${'sandboxId'}}`, encodeURIComponent(String(sandboxId)))
					.replace(`{${'sessionId'}}`, encodeURIComponent(String(sessionId)))
					.replace(`{${'commandId'}}`, encodeURIComponent(String(commandId)));
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {string} commandId
		 * @param {string | null} [follow]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getCommandLogs: async (
			sandboxId: string,
			sessionId: string,
			commandId: string,
			follow?: string | null,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('getCommandLogs', 'sandboxId', sandboxId);
			// verify required parameter 'sessionId' is not null or undefined
			assertParamExists('getCommandLogs', 'sessionId', sessionId);
			// verify required parameter 'commandId' is not null or undefined
			assertParamExists('getCommandLogs', 'commandId', commandId);
			const localVarPath =
				`/toolbox/{sandboxId}/process/session/{sessionId}/command/{commandId}/logs`
					.replace(`{${'sandboxId'}}`, encodeURIComponent(String(sandboxId)))
					.replace(`{${'sessionId'}}`, encodeURIComponent(String(sessionId)))
					.replace(`{${'commandId'}}`, encodeURIComponent(String(commandId)));
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			if (follow !== undefined) {
				localVarQueryParameter['follow'] = follow;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getSession: async (
			sandboxId: string,
			sessionId: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('getSession', 'sandboxId', sandboxId);
			// verify required parameter 'sessionId' is not null or undefined
			assertParamExists('getSession', 'sessionId', sessionId);
			const localVarPath = `/toolbox/{sandboxId}/process/session/{sessionId}`
				.replace(`{${'sandboxId'}}`, encodeURIComponent(String(sandboxId)))
				.replace(`{${'sessionId'}}`, encodeURIComponent(String(sessionId)));
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		listSessions: async (
			sandboxId: string,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('listSessions', 'sandboxId', sandboxId);
			const localVarPath = `/toolbox/{sandboxId}/process/session`.replace(
				`{${'sandboxId'}}`,
				encodeURIComponent(String(sandboxId))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {CodeRunRequest} codeRunRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		runCode: async (
			sandboxId: string,
			codeRunRequest: CodeRunRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('runCode', 'sandboxId', sandboxId);
			// verify required parameter 'codeRunRequest' is not null or undefined
			assertParamExists('runCode', 'codeRunRequest', codeRunRequest);
			const localVarPath = `/toolbox/{sandboxId}/process/code-run`.replace(
				`{${'sandboxId'}}`,
				encodeURIComponent(String(sandboxId))
			);
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				codeRunRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {SessionExecuteRequest} sessionExecuteRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		sessionExecuteCommand: async (
			sandboxId: string,
			sessionId: string,
			sessionExecuteRequest: SessionExecuteRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'sandboxId' is not null or undefined
			assertParamExists('sessionExecuteCommand', 'sandboxId', sandboxId);
			// verify required parameter 'sessionId' is not null or undefined
			assertParamExists('sessionExecuteCommand', 'sessionId', sessionId);
			// verify required parameter 'sessionExecuteRequest' is not null or undefined
			assertParamExists(
				'sessionExecuteCommand',
				'sessionExecuteRequest',
				sessionExecuteRequest
			);
			const localVarPath =
				`/toolbox/{sandboxId}/process/session/{sessionId}/exec`
					.replace(`{${'sandboxId'}}`, encodeURIComponent(String(sandboxId)))
					.replace(`{${'sessionId'}}`, encodeURIComponent(String(sessionId)));
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				sessionExecuteRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
	};
};

/**
 * ToolboxProcessApi - functional programming interface
 * @export
 */
export const ToolboxProcessApiFp = function (configuration?: Configuration) {
	const localVarAxiosParamCreator =
		ToolboxProcessApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {CreateSessionRequest} createSessionRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async createSession(
			sandboxId: string,
			createSessionRequest: CreateSessionRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.createSession(
				sandboxId,
				createSessionRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.createSession']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteSession(
			sandboxId: string,
			sessionId: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSession(
				sandboxId,
				sessionId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.deleteSession']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {ExecuteRequest} executeRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async executeCommand(
			sandboxId: string,
			executeRequest: ExecuteRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<ExecuteResponse>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.executeCommand(
				sandboxId,
				executeRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.executeCommand']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {string} commandId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getCommand(
			sandboxId: string,
			sessionId: string,
			commandId: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommandDto>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getCommand(
				sandboxId,
				sessionId,
				commandId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.getCommand']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {string} commandId
		 * @param {string | null} [follow]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getCommandLogs(
			sandboxId: string,
			sessionId: string,
			commandId: string,
			follow?: string | null,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getCommandLogs(
				sandboxId,
				sessionId,
				commandId,
				follow,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.getCommandLogs']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getSession(
			sandboxId: string,
			sessionId: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SessionDto>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getSession(
				sandboxId,
				sessionId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.getSession']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async listSessions(
			sandboxId: string,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<Array<SessionDto>>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.listSessions(
				sandboxId,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.listSessions']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {CodeRunRequest} codeRunRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async runCode(
			sandboxId: string,
			codeRunRequest: CodeRunRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<CodeRunResponse>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.runCode(
				sandboxId,
				codeRunRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.runCode']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {SessionExecuteRequest} sessionExecuteRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async sessionExecuteCommand(
			sandboxId: string,
			sessionId: string,
			sessionExecuteRequest: SessionExecuteRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<SessionExecuteResponse>
		> {
			const localVarAxiosArgs =
				await localVarAxiosParamCreator.sessionExecuteCommand(
					sandboxId,
					sessionId,
					sessionExecuteRequest,
					options
				);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['ToolboxProcessApi.sessionExecuteCommand']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
	};
};

/**
 * ToolboxProcessApi - factory interface
 * @export
 */
export const ToolboxProcessApiFactory = function (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) {
	const localVarFp = ToolboxProcessApiFp(configuration);
	return {
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {CreateSessionRequest} createSessionRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		createSession(
			sandboxId: string,
			createSessionRequest: CreateSessionRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.createSession(sandboxId, createSessionRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteSession(
			sandboxId: string,
			sessionId: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.deleteSession(sandboxId, sessionId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {ExecuteRequest} executeRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		executeCommand(
			sandboxId: string,
			executeRequest: ExecuteRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<ExecuteResponse> {
			return localVarFp
				.executeCommand(sandboxId, executeRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {string} commandId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getCommand(
			sandboxId: string,
			sessionId: string,
			commandId: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<CommandDto> {
			return localVarFp
				.getCommand(sandboxId, sessionId, commandId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {string} commandId
		 * @param {string | null} [follow]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getCommandLogs(
			sandboxId: string,
			sessionId: string,
			commandId: string,
			follow?: string | null,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.getCommandLogs(sandboxId, sessionId, commandId, follow, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getSession(
			sandboxId: string,
			sessionId: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<SessionDto> {
			return localVarFp
				.getSession(sandboxId, sessionId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		listSessions(
			sandboxId: string,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Array<SessionDto>> {
			return localVarFp
				.listSessions(sandboxId, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {CodeRunRequest} codeRunRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		runCode(
			sandboxId: string,
			codeRunRequest: CodeRunRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<CodeRunResponse> {
			return localVarFp
				.runCode(sandboxId, codeRunRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string} sandboxId ID of the sandbox
		 * @param {string} sessionId
		 * @param {SessionExecuteRequest} sessionExecuteRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		sessionExecuteCommand(
			sandboxId: string,
			sessionId: string,
			sessionExecuteRequest: SessionExecuteRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<SessionExecuteResponse> {
			return localVarFp
				.sessionExecuteCommand(
					sandboxId,
					sessionId,
					sessionExecuteRequest,
					options
				)
				.then((request) => request(axios, basePath));
		},
	};
};

/**
 * ToolboxProcessApi - object-oriented interface
 * @export
 * @class ToolboxProcessApi
 * @extends {BaseAPI}
 */
export class ToolboxProcessApi extends BaseAPI {
	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {CreateSessionRequest} createSessionRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public createSession(
		sandboxId: string,
		createSessionRequest: CreateSessionRequest,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.createSession(sandboxId, createSessionRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {string} sessionId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public deleteSession(
		sandboxId: string,
		sessionId: string,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.deleteSession(sandboxId, sessionId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {ExecuteRequest} executeRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public executeCommand(
		sandboxId: string,
		executeRequest: ExecuteRequest,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.executeCommand(sandboxId, executeRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {string} sessionId
	 * @param {string} commandId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public getCommand(
		sandboxId: string,
		sessionId: string,
		commandId: string,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.getCommand(sandboxId, sessionId, commandId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {string} sessionId
	 * @param {string} commandId
	 * @param {string | null} [follow]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public getCommandLogs(
		sandboxId: string,
		sessionId: string,
		commandId: string,
		follow?: string | null,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.getCommandLogs(sandboxId, sessionId, commandId, follow, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {string} sessionId
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public getSession(
		sandboxId: string,
		sessionId: string,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.getSession(sandboxId, sessionId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public listSessions(sandboxId: string, options?: RawAxiosRequestConfig) {
		return ToolboxProcessApiFp(this.configuration)
			.listSessions(sandboxId, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {CodeRunRequest} codeRunRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public runCode(
		sandboxId: string,
		codeRunRequest: CodeRunRequest,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.runCode(sandboxId, codeRunRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string} sandboxId ID of the sandbox
	 * @param {string} sessionId
	 * @param {SessionExecuteRequest} sessionExecuteRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof ToolboxProcessApi
	 */
	public sessionExecuteCommand(
		sandboxId: string,
		sessionId: string,
		sessionExecuteRequest: SessionExecuteRequest,
		options?: RawAxiosRequestConfig
	) {
		return ToolboxProcessApiFp(this.configuration)
			.sessionExecuteCommand(
				sandboxId,
				sessionId,
				sessionExecuteRequest,
				options
			)
			.then((request) => request(this.axios, this.basePath));
	}
}
