// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`archive_sandbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ArchiveSandboxError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_backup`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateBackupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_sandbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateSandboxError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_sandbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSandboxError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_build_logs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBuildLogsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_port_preview_url`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPortPreviewUrlError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_sandbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSandboxError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_sandboxes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSandboxesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_sandboxes_paginated`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSandboxesPaginatedError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`replace_labels`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReplaceLabelsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_auto_delete_interval`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetAutoDeleteIntervalError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_autostop_interval`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetAutostopIntervalError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_sandbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartSandboxError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`stop_sandbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StopSandboxError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_last_activity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateLastActivityError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_public_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePublicStatusError {
    UnknownValue(serde_json::Value),
}

pub async fn archive_sandbox(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<ArchiveSandboxError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/archive",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ArchiveSandboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn create_backup(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<CreateBackupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/backup",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateBackupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn create_sandbox(
    configuration: &configuration::Configuration,
    create_sandbox: models::CreateSandbox,
    x_snapflow_organization_id: Option<&str>,
) -> Result<models::Sandbox, Error<CreateSandboxError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_create_sandbox = create_sandbox;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!("{}/sandbox", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_create_sandbox);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Sandbox`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Sandbox`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateSandboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn delete_sandbox(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<DeleteSandboxError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteSandboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_build_logs(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
    follow: Option<bool>,
) -> Result<(), Error<GetBuildLogsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;
    let p_follow = follow;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/build-logs",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_follow {
        req_builder = req_builder.query(&[("follow", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBuildLogsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_port_preview_url(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    port: i32,
    x_snapflow_organization_id: Option<&str>,
) -> Result<models::PortPreviewUrl, Error<GetPortPreviewUrlError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_port = port;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/ports/{port}/preview-url",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id),
        port = p_port
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PortPreviewUrl`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PortPreviewUrl`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPortPreviewUrlError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_sandbox(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
) -> Result<models::Sandbox, Error<GetSandboxError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Sandbox`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Sandbox`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSandboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_sandboxes(
    configuration: &configuration::Configuration,
    x_snapflow_organization_id: Option<&str>,
    verbose: Option<bool>,
    labels: Option<&str>,
    include_errored_deleted: Option<bool>,
) -> Result<Vec<models::Sandbox>, Error<ListSandboxesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_x_snapflow_organization_id = x_snapflow_organization_id;
    let p_verbose = verbose;
    let p_labels = labels;
    let p_include_errored_deleted = include_errored_deleted;

    let uri_str = format!("{}/sandbox", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_verbose {
        req_builder = req_builder.query(&[("verbose", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_labels {
        req_builder = req_builder.query(&[("labels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include_errored_deleted {
        req_builder = req_builder.query(&[("includeErroredDeleted", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Sandbox&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Sandbox&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSandboxesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_sandboxes_paginated(
    configuration: &configuration::Configuration,
    x_snapflow_organization_id: Option<&str>,
    page: Option<i64>,
    limit: Option<i64>,
    labels: Option<&str>,
    include_errored_deleted: Option<bool>,
) -> Result<models::PaginatedSandboxes, Error<ListSandboxesPaginatedError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_x_snapflow_organization_id = x_snapflow_organization_id;
    let p_page = page;
    let p_limit = limit;
    let p_labels = labels;
    let p_include_errored_deleted = include_errored_deleted;

    let uri_str = format!("{}/sandbox/paginated", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_labels {
        req_builder = req_builder.query(&[("labels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include_errored_deleted {
        req_builder = req_builder.query(&[("includeErroredDeleted", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PaginatedSandboxes`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PaginatedSandboxes`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSandboxesPaginatedError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn replace_labels(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    update_sandbox_labels: models::UpdateSandboxLabels,
    x_snapflow_organization_id: Option<&str>,
) -> Result<models::UpdateSandboxLabels, Error<ReplaceLabelsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_update_sandbox_labels = update_sandbox_labels;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/labels",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_update_sandbox_labels);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateSandboxLabels`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateSandboxLabels`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ReplaceLabelsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn set_auto_delete_interval(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    interval: i32,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<SetAutoDeleteIntervalError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_interval = interval;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/autodelete/{interval}",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id),
        interval = p_interval
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SetAutoDeleteIntervalError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn set_autostop_interval(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    interval: i32,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<SetAutostopIntervalError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_interval = interval;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/autostop/{interval}",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id),
        interval = p_interval
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SetAutostopIntervalError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn start_sandbox(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
) -> Result<models::Sandbox, Error<StartSandboxError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/start",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Sandbox`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Sandbox`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StartSandboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn stop_sandbox(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<StopSandboxError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/stop",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StopSandboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn update_last_activity(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<UpdateLastActivityError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/activity",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateLastActivityError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn update_public_status(
    configuration: &configuration::Configuration,
    sandbox_id: &str,
    is_public: bool,
    x_snapflow_organization_id: Option<&str>,
) -> Result<(), Error<UpdatePublicStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_sandbox_id = sandbox_id;
    let p_is_public = is_public;
    let p_x_snapflow_organization_id = x_snapflow_organization_id;

    let uri_str = format!(
        "{}/sandbox/{sandboxId}/public/{isPublic}",
        configuration.base_path,
        sandboxId = crate::apis::urlencode(p_sandbox_id),
        isPublic = p_is_public
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_snapflow_organization_id {
        req_builder = req_builder.header("x-snapflow-organization-id", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdatePublicStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
