/*
 * Copyright (c) 2026 Snapflow. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Copyright 2025 Snapflow
 * SPDX-License-Identifier: Apache-2.0
 */

/* tslint:disable */
/* eslint-disable */
/**
 * Snapflow Node API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	setApiKeyToObject,
	setBasicAuthToObject,
	setBearerAuthToObject,
	setOAuthToObject,
	setSearchParams,
	serializeDataIfNeeded,
	toPathString,
	createRequestFunction,
} from '../common';
// @ts-ignore
import {
	BASE_PATH,
	COLLECTION_FORMATS,
	type RequestArgs,
	BaseAPI,
	RequiredError,
	operationServerMap,
} from '../base';
// @ts-ignore
import type { GitAddRequest } from '../models';
// @ts-ignore
import type { GitBranchRequest } from '../models';
// @ts-ignore
import type { GitCheckoutRequest } from '../models';
// @ts-ignore
import type { GitCloneRequest } from '../models';
// @ts-ignore
import type { GitCommitInfo } from '../models';
// @ts-ignore
import type { GitCommitRequest } from '../models';
// @ts-ignore
import type { GitCommitResponse } from '../models';
// @ts-ignore
import type { GitRepoRequest } from '../models';
// @ts-ignore
import type { GitStatus } from '../models';
// @ts-ignore
import type { ListBranchResponse } from '../models';
/**
 * GitApi - axios parameter creator
 * @export
 */
export const GitApiAxiosParamCreator = function (
	configuration?: Configuration
) {
	return {
		/**
		 *
		 * @param {GitCloneRequest} gitCloneRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		cloneRepository: async (
			gitCloneRequest: GitCloneRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitCloneRequest' is not null or undefined
			assertParamExists('cloneRepository', 'gitCloneRequest', gitCloneRequest);
			const localVarPath = `/git/clone`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitCloneRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {GitBranchRequest} gitBranchRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		createBranch: async (
			gitBranchRequest: GitBranchRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitBranchRequest' is not null or undefined
			assertParamExists('createBranch', 'gitBranchRequest', gitBranchRequest);
			const localVarPath = `/git/branches`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitBranchRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {GitBranchRequest} gitBranchRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteBranch: async (
			gitBranchRequest: GitBranchRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitBranchRequest' is not null or undefined
			assertParamExists('deleteBranch', 'gitBranchRequest', gitBranchRequest);
			const localVarPath = `/git/branches`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'DELETE',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitBranchRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getGitHistory: async (
			path?: string | null,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			const localVarPath = `/git/history`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			if (path !== undefined) {
				localVarQueryParameter['path'] = path;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getGitStatus: async (
			path?: string | null,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			const localVarPath = `/git/status`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			if (path !== undefined) {
				localVarQueryParameter['path'] = path;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {GitAddRequest} gitAddRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitAddFiles: async (
			gitAddRequest: GitAddRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitAddRequest' is not null or undefined
			assertParamExists('gitAddFiles', 'gitAddRequest', gitAddRequest);
			const localVarPath = `/git/add`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitAddRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {GitCheckoutRequest} gitCheckoutRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitCheckout: async (
			gitCheckoutRequest: GitCheckoutRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitCheckoutRequest' is not null or undefined
			assertParamExists(
				'gitCheckout',
				'gitCheckoutRequest',
				gitCheckoutRequest
			);
			const localVarPath = `/git/checkout`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitCheckoutRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {GitCommitRequest} gitCommitRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitCommit: async (
			gitCommitRequest: GitCommitRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitCommitRequest' is not null or undefined
			assertParamExists('gitCommit', 'gitCommitRequest', gitCommitRequest);
			const localVarPath = `/git/commit`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitCommitRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {GitRepoRequest} gitRepoRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitPull: async (
			gitRepoRequest: GitRepoRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitRepoRequest' is not null or undefined
			assertParamExists('gitPull', 'gitRepoRequest', gitRepoRequest);
			const localVarPath = `/git/pull`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitRepoRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {GitRepoRequest} gitRepoRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitPush: async (
			gitRepoRequest: GitRepoRequest,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			// verify required parameter 'gitRepoRequest' is not null or undefined
			assertParamExists('gitPush', 'gitRepoRequest', gitRepoRequest);
			const localVarPath = `/git/push`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'POST',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			localVarHeaderParameter['Content-Type'] = 'application/json';

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};
			localVarRequestOptions.data = serializeDataIfNeeded(
				gitRepoRequest,
				localVarRequestOptions,
				configuration
			);

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		listBranches: async (
			path?: string | null,
			options: RawAxiosRequestConfig = {}
		): Promise<RequestArgs> => {
			const localVarPath = `/git/branches`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (configuration) {
				baseOptions = configuration.baseOptions;
			}

			const localVarRequestOptions = {
				method: 'GET',
				...baseOptions,
				...options,
			};
			const localVarHeaderParameter = {} as any;
			const localVarQueryParameter = {} as any;

			if (path !== undefined) {
				localVarQueryParameter['path'] = path;
			}

			setSearchParams(localVarUrlObj, localVarQueryParameter);
			let headersFromBaseOptions =
				baseOptions && baseOptions.headers ? baseOptions.headers : {};
			localVarRequestOptions.headers = {
				...localVarHeaderParameter,
				...headersFromBaseOptions,
				...options.headers,
			};

			return {
				url: toPathString(localVarUrlObj),
				options: localVarRequestOptions,
			};
		},
	};
};

/**
 * GitApi - functional programming interface
 * @export
 */
export const GitApiFp = function (configuration?: Configuration) {
	const localVarAxiosParamCreator = GitApiAxiosParamCreator(configuration);
	return {
		/**
		 *
		 * @param {GitCloneRequest} gitCloneRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async cloneRepository(
			gitCloneRequest: GitCloneRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.cloneRepository(
				gitCloneRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.cloneRepository']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {GitBranchRequest} gitBranchRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async createBranch(
			gitBranchRequest: GitBranchRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.createBranch(
				gitBranchRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.createBranch']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {GitBranchRequest} gitBranchRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async deleteBranch(
			gitBranchRequest: GitBranchRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBranch(
				gitBranchRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.deleteBranch']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getGitHistory(
			path?: string | null,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<Array<GitCommitInfo>>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getGitHistory(
				path,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.getGitHistory']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async getGitStatus(
			path?: string | null,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GitStatus>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.getGitStatus(
				path,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.getGitStatus']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {GitAddRequest} gitAddRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async gitAddFiles(
			gitAddRequest: GitAddRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.gitAddFiles(
				gitAddRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.gitAddFiles']?.[localVarOperationServerIndex]
					?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {GitCheckoutRequest} gitCheckoutRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async gitCheckout(
			gitCheckoutRequest: GitCheckoutRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.gitCheckout(
				gitCheckoutRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.gitCheckout']?.[localVarOperationServerIndex]
					?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {GitCommitRequest} gitCommitRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async gitCommit(
			gitCommitRequest: GitCommitRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<GitCommitResponse>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.gitCommit(
				gitCommitRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.gitCommit']?.[localVarOperationServerIndex]
					?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {GitRepoRequest} gitRepoRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async gitPull(
			gitRepoRequest: GitRepoRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.gitPull(
				gitRepoRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.gitPull']?.[localVarOperationServerIndex]
					?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {GitRepoRequest} gitRepoRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async gitPush(
			gitRepoRequest: GitRepoRequest,
			options?: RawAxiosRequestConfig
		): Promise<
			(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.gitPush(
				gitRepoRequest,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.gitPush']?.[localVarOperationServerIndex]
					?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		async listBranches(
			path?: string | null,
			options?: RawAxiosRequestConfig
		): Promise<
			(
				axios?: AxiosInstance,
				basePath?: string
			) => AxiosPromise<ListBranchResponse>
		> {
			const localVarAxiosArgs = await localVarAxiosParamCreator.listBranches(
				path,
				options
			);
			const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
			const localVarOperationServerBasePath =
				operationServerMap['GitApi.listBranches']?.[
					localVarOperationServerIndex
				]?.url;
			return (axios, basePath) =>
				createRequestFunction(
					localVarAxiosArgs,
					globalAxios,
					BASE_PATH,
					configuration
				)(axios, localVarOperationServerBasePath || basePath);
		},
	};
};

/**
 * GitApi - factory interface
 * @export
 */
export const GitApiFactory = function (
	configuration?: Configuration,
	basePath?: string,
	axios?: AxiosInstance
) {
	const localVarFp = GitApiFp(configuration);
	return {
		/**
		 *
		 * @param {GitCloneRequest} gitCloneRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		cloneRepository(
			gitCloneRequest: GitCloneRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.cloneRepository(gitCloneRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {GitBranchRequest} gitBranchRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		createBranch(
			gitBranchRequest: GitBranchRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.createBranch(gitBranchRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {GitBranchRequest} gitBranchRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		deleteBranch(
			gitBranchRequest: GitBranchRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.deleteBranch(gitBranchRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getGitHistory(
			path?: string | null,
			options?: RawAxiosRequestConfig
		): AxiosPromise<Array<GitCommitInfo>> {
			return localVarFp
				.getGitHistory(path, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		getGitStatus(
			path?: string | null,
			options?: RawAxiosRequestConfig
		): AxiosPromise<GitStatus> {
			return localVarFp
				.getGitStatus(path, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {GitAddRequest} gitAddRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitAddFiles(
			gitAddRequest: GitAddRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.gitAddFiles(gitAddRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {GitCheckoutRequest} gitCheckoutRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitCheckout(
			gitCheckoutRequest: GitCheckoutRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.gitCheckout(gitCheckoutRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {GitCommitRequest} gitCommitRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitCommit(
			gitCommitRequest: GitCommitRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<GitCommitResponse> {
			return localVarFp
				.gitCommit(gitCommitRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {GitRepoRequest} gitRepoRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitPull(
			gitRepoRequest: GitRepoRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.gitPull(gitRepoRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {GitRepoRequest} gitRepoRequest
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		gitPush(
			gitRepoRequest: GitRepoRequest,
			options?: RawAxiosRequestConfig
		): AxiosPromise<void> {
			return localVarFp
				.gitPush(gitRepoRequest, options)
				.then((request) => request(axios, basePath));
		},
		/**
		 *
		 * @param {string | null} [path]
		 * @param {*} [options] Override http request option.
		 * @throws {RequiredError}
		 */
		listBranches(
			path?: string | null,
			options?: RawAxiosRequestConfig
		): AxiosPromise<ListBranchResponse> {
			return localVarFp
				.listBranches(path, options)
				.then((request) => request(axios, basePath));
		},
	};
};

/**
 * GitApi - object-oriented interface
 * @export
 * @class GitApi
 * @extends {BaseAPI}
 */
export class GitApi extends BaseAPI {
	/**
	 *
	 * @param {GitCloneRequest} gitCloneRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public cloneRepository(
		gitCloneRequest: GitCloneRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.cloneRepository(gitCloneRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {GitBranchRequest} gitBranchRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public createBranch(
		gitBranchRequest: GitBranchRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.createBranch(gitBranchRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {GitBranchRequest} gitBranchRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public deleteBranch(
		gitBranchRequest: GitBranchRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.deleteBranch(gitBranchRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string | null} [path]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public getGitHistory(path?: string | null, options?: RawAxiosRequestConfig) {
		return GitApiFp(this.configuration)
			.getGitHistory(path, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string | null} [path]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public getGitStatus(path?: string | null, options?: RawAxiosRequestConfig) {
		return GitApiFp(this.configuration)
			.getGitStatus(path, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {GitAddRequest} gitAddRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public gitAddFiles(
		gitAddRequest: GitAddRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.gitAddFiles(gitAddRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {GitCheckoutRequest} gitCheckoutRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public gitCheckout(
		gitCheckoutRequest: GitCheckoutRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.gitCheckout(gitCheckoutRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {GitCommitRequest} gitCommitRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public gitCommit(
		gitCommitRequest: GitCommitRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.gitCommit(gitCommitRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {GitRepoRequest} gitRepoRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public gitPull(
		gitRepoRequest: GitRepoRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.gitPull(gitRepoRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {GitRepoRequest} gitRepoRequest
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public gitPush(
		gitRepoRequest: GitRepoRequest,
		options?: RawAxiosRequestConfig
	) {
		return GitApiFp(this.configuration)
			.gitPush(gitRepoRequest, options)
			.then((request) => request(this.axios, this.basePath));
	}

	/**
	 *
	 * @param {string | null} [path]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof GitApi
	 */
	public listBranches(path?: string | null, options?: RawAxiosRequestConfig) {
		return GitApiFp(this.configuration)
			.listBranches(path, options)
			.then((request) => request(this.axios, this.basePath));
	}
}
