// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow Executor API
 *
 * Snapflow Executor API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildImageRequestDto {
    #[serde(rename = "context", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub context: Option<Option<Vec<String>>>,
    #[serde(rename = "dockerfile")]
    pub dockerfile: String,
    /// Image ID and tag or the build's hash
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(rename = "pushToInternalRegistry", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub push_to_internal_registry: Option<Option<bool>>,
    #[serde(rename = "registry", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub registry: Option<Option<Box<models::RegistryDto>>>,
}

impl BuildImageRequestDto {
    pub fn new(dockerfile: String, image: String, organization_id: String) -> BuildImageRequestDto {
        BuildImageRequestDto {
            context: None,
            dockerfile,
            image,
            organization_id,
            push_to_internal_registry: None,
            registry: None,
        }
    }
}

