/*
 * Snapflow Executor API
 *
 * Snapflow Executor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBackupDto {
    /// Full backup image reference: \"registry/project/backup-{sandbox-id}:{timestamp}\"
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "registry")]
    pub registry: Box<models::RegistryDto>,
}

impl CreateBackupDto {
    pub fn new(image: String, registry: models::RegistryDto) -> CreateBackupDto {
        CreateBackupDto {
            image,
            registry: Box::new(registry),
        }
    }
}
