// Copyright (c) 2026 Snapflow. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Snapflow Executor API
 *
 * Snapflow Executor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxInfoResponse {
    #[serde(
        rename = "backupError",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub backup_error: Option<Option<String>>,
    #[serde(rename = "backupState")]
    pub backup_state: models::BackupState,
    #[serde(rename = "state")]
    pub state: models::SandboxState,
}

impl SandboxInfoResponse {
    pub fn new(
        backup_state: models::BackupState,
        state: models::SandboxState,
    ) -> SandboxInfoResponse {
        SandboxInfoResponse {
            backup_error: None,
            backup_state,
            state,
        }
    }
}
