version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: ./apps/proxy/Dockerfile
    container_name: snapflow_proxy
    restart: always
    ports:
      - "4000:4000"
    environment:
      - SNAPFLOW_API_URL=${SNAPFLOW_API_URL}
      - PROXY_PORT=${PROXY_PORT}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_API_KEY=${PROXY_API_KEY}
      - OIDC_DOMAIN=${OIDC_DOMAIN}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - proxy-redis
    networks:
      - proxy-network

  proxy-redis:
    image: redis:latest
    container_name: snapflow_proxy_redis
    restart: always
    expose:
      - "6379"
    volumes:
      - proxy_redis_data:/data
    networks:
      - proxy-network

volumes:
  proxy_redis_data:

networks:
  proxy-network:
    driver: bridge